### ISSUE TITLE
Clear Canvas feature

### ISSUE THREAD

**Issue by Pritirekha23** [singodiyashubham87/Draw-it-out#1]
Clearing the canvas with a single click is a useful feature, but the issue is that the user cannot remove specific parts of the canvas. Therefore, I suggest adding a button that allows the user to adjust the area to be cleared.

**Comment by singodiyashubham87** [comment]
@Pritirekha23 Thank you so much pritirekha for the suggestion, It's a good one.
I'll work on it. & if you are interested to contribute then you are most welcome.

**Comment by Pritirekha23** [comment]
I will work on it.

**Comment by singodiyashubham87** [comment]
@Pritirekha23 I have assigned the issue to you. 
Best of Luck.

**Comment by singodiyashubham87** [comment]
@Pritirekha23 Are you working on the issue?

**Comment by Pritirekha23** [comment]
Yes , soon I will push the code.

**Comment by singodiyashubham87** [comment]
@Pritirekha23 Are you still working on the issue or should I assign to someone else?

**Comment by Pritirekha23** [comment]
I have added the icons and facing issues in the functionality.

**Comment by singodiyashubham87** [comment]
@Pritirekha23 Are you done working on the issue?
