### ISSUE TITLE
[FEAT] Add a animated Onboarding tour of website.

### ISSUE THREAD

**Issue by Rahulsingh1939** [singodiyashubham87/Draw-it-out#101]
The animated onboarding tour feature provides new users with a guided introduction to our website's interface,

Engaging animations will be used to draw attention to important elements of the interface.
By using React Onboarding Libraries, we can implement a quick go through of our website .

Eg.
![react-joyride-example](https://github.com/singodiyashubham87/Draw-it-out/assets/56185613/1c7b9990-c5c4-40ed-ab77-74b471b744c4)

**Comment by Rahulsingh1939** [comment]
I would like to work on this feature @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@Rahulsingh1939 That's really a good feature.
Assigned you the issue, Best of Luck!

**Comment by Rahulsingh1939** [comment]
@singodiyashubham87 I have implemented a quick walkthrough of our website.
![drawIt](https://github.com/singodiyashubham87/Draw-it-out/assets/56185613/f2e4f4b2-d20f-4c6a-a95e-ec5734ac56fa)

Please review the PR #125
