### ISSUE TITLE
[FEAT] : Adding Color filler tool to the canvas.

### ISSUE THREAD

**Issue by poojaverma9578** [singodiyashubham87/Draw-it-out#104]
Sometimes it is necessary or feels good to have a canvas of our colour choice. This functionality should be added into the website. I want to add this feature while contributing to the Gssoc 2024 label. Please assign this task to me and add the required Gssoc Label.

**Comment by singodiyashubham87** [comment]
@poojaverma9578 There is already option to have the background color of canvas according to our choice. There are color palattes provided for this already, Kindly raise new issues.
