### ISSUE TITLE
[FEAT] Added a reset button 

### ISSUE THREAD

**Issue by Arghyadeep09** [singodiyashubham87/Draw-it-out#105]
Problem:

The website lacks a user-friendly feature to revert the canvas color to its default state after it has been changed. Users are currently unable to restore the default canvas color without reloading the entire page, leading to a suboptimal user experience.

Solution :

To address the issue of users being unable to revert the canvas color to its default state without reloading the entire page, a solution was implemented by adding a button. This button, when clicked, resets the canvas to its original color, enhancing user experience and providing a convenient way to restore the canvas to its default state.

Screenshot:
![Screenshot 2024-05-13 020043](https://github.com/singodiyashubham87/Draw-it-out/assets/90449806/edfd0225-69a5-4f67-9523-6c2cc43f32a9)

Video Solution:

https://github.com/singodiyashubham87/Draw-it-out/assets/90449806/de81df2d-c2b8-4740-97f2-dcd32f7077d3

**Comment by Arghyadeep09** [comment]
Under GSSOC 24, Please assign the work to me!

**Comment by singodiyashubham87** [comment]
@Arghyadeep09 I don't think there is a need of this feature, already the user has the option to change background color to the one of their choice, So they can use the color palatte to make it same as before.
