### ISSUE TITLE
[BUG] ; Responsive Issue

### ISSUE THREAD

**Issue by sivaprasath2004** [singodiyashubham87/Draw-it-out#107]
**Describe the bug**
- In `Tab` and `mobile` screen doesn't proper Responsive

**To Reproduce**
1. Go to page
2. Click on inspect
3. Change to the screen size `400 to 900` 

**Expected behavior**
- All of the device can be perfect responsive but is not responsive.

## **Screenshots**
![Screenshot from 2024-05-13 18-17-15](https://github.com/singodiyashubham87/Draw-it-out/assets/121082414/8493586c-f202-4908-a40b-bfb93a28839b)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device:Realme 8
 - OS: Android 12
 - Browser : chrome

**Comment by 0xabdulkhalid** [comment]
This must need to be fixed, So i assigning this issue to you @sivaprasath2004.

I've inspected the code for verifying the bug, you don't need to add new rules to fix this layout distortion instead you simply remove some `@media` queries to fix this issue.

Hope you understood, create a PR once you fixed this issue!
