### ISSUE TITLE
Include a redo,undo and erase option

### ISSUE THREAD

**Issue by kesharwaniyanshi** [singodiyashubham87/Draw-it-out#109]
#### Description
Currently, the application lacks the ability to undo or redo drawing actions, as well as an option to erase or clear the canvas. This feature would provide users with greater control and flexibility when creating drawings, allowing them to correct mistakes or experiment more freely.

#### Proposed Solution
Implement the following functionalities:

1. **Undo**: Add a button that allows users to undo the last drawing action performed on the canvas.
2. **Redo**: Add a button that allows users to redo the last undone action, effectively reversing the undo operation.
3. **Erase**: Add a button or tool that allows users to erase or clear specific areas of the canvas by drawing over them.

#### Implementation Suggestions
- Utilize React's state management to keep track of the drawing actions performed on the canvas.
- Maintain a stack or array to store the canvas states after each drawing action, enabling the undo and redo functionalities.
- For the erase tool, consider implementing a separate mode or tool that allows users to draw with a specific "erase" color or transparency.

#### Benefits
- Improved user experience by providing more control and flexibility over the drawing process.
- Reduced frustration by allowing users to correct mistakes or experiment without having to start from scratch.
- Enhanced productivity by enabling users to iterate and refine their drawings more efficiently.

#### Additional Considerations
- Ensure that the undo, redo, and erase functionalities work seamlessly with other existing tools and features.
- Consider adding keyboard shortcuts or hotkeys for common actions to enhance accessibility and efficiency.
- Provide clear visual feedback or indicators to users when undo, redo, or erase actions are performed.

Please assign me this issue.

**Comment by 0xabdulkhalid** [comment]
Oops! @kesharwaniyanshi, There's an existing issue about adding Undo / Redo functionality. (#43)

So this issue is a duplicate one, so we can't allow you to work on this issue.

I'm closing this for now, now you can a new issue for contributing. Thank you!
