### ISSUE TITLE
Add volume button and controls 

### ISSUE THREAD

**Issue by Riddhi162** [singodiyashubham87/Draw-it-out#113]
We can add volume controls to it like when someone creates a new drawing some volume is triggered.
Volume on and off throughout the drawing session must be there.

**Comment by singodiyashubham87** [comment]
@Riddhi162 What is the significance of sound when creating a drawing?
Don't you think it'll distract the user instead.

**Comment by Riddhi162** [comment]
> @Riddhi162 What is the significance of sound when creating a drawing? Don't you think it'll distract the user instead.

we can provide sounds when suppose user selects a new canvas it will make a pop sound or something or when erases,redo or undo like that and if dont want to provide sound throughout the game we can avoid that 
Or else we can keep a feature to disable the sound

**Comment by singodiyashubham87** [comment]
@Riddhi162 Maybe you got it wrong, This web-app is not a game, it's a whiteboard applications to draw sketches, brainstorm random ideas, etc. I don't think there is any significant need of sounds.
We highly appreciate your enthusiasm for contribution.
Kindly check out other issues or create new useful ones to resolve.
