### ISSUE TITLE
[FEAT] Colour palette can be shifted up

### ISSUE THREAD

**Issue by Rakshit-gen** [singodiyashubham87/Draw-it-out#118]
**Is your feature request related to a problem? Please describe.**
The colour palette on desktop can be pushed up so that user doesn't have to scroll this much to reach the black and white colours

**Additional context**
Assign this issue to me please as a GSSoC '24 contributor.

**Comment by aishwaryeaah** [comment]
Under GSSOC 24, Please assign the work to me!

**Comment by singodiyashubham87** [comment]
@Rakshit-gen Not needed.
