### ISSUE TITLE
[BUG] changing the thickness of the pen resets the canvas

### ISSUE THREAD

**Issue by AMISH-KHAN** [singodiyashubham87/Draw-it-out#120]
**Describe the bug**

When we change the thickness of the pen it resets the canvas making the drawing disappear.

https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/7fa506e3-334e-453c-a2ba-ffb7f5d3b5eb

Please assign this issue to me Under GSSOC and add necessary labels

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Duplicate of #2
