### ISSUE TITLE
[FEAT] Adding hide/show button for canvas background color

### ISSUE THREAD

**Issue by AMISH-KHAN** [singodiyashubham87/Draw-it-out#121]
**Is your feature request related to a problem? Please describe.**

In the current UI there is a list of background color on left.
we can add the hide and show button Which will enhance the UI.

https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/f7bcff9f-3ca3-4bf3-8c31-849a2ee5e70c

Please assign this issue to me under GSSoC and add necessary labels

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN This feature has already been implemented and there is an option to hide the tools and colors both.
Can you explain what uniqueness will this add to the application?

**Comment by AMISH-KHAN** [comment]
> @AMISH-KHAN This feature has already been implemented and there is an option to hide the tools and colors both. Can you explain what uniqueness will this add to the application?

The current UI has a feature to select any color from color picker but still it also has the list of other colors.

This causes the UI to overFlow from the screen.

https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/b604ba1c-0265-4d39-a39b-b75d970d6958

now Here we can either keep both color picker and other colors Tiles but then we need to implement my suggested feature to enhance UI and and get rid of unnecessary Scrolling.

or we can keep only color picker and get rid of all other color tiles

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Assigned you the issue, Best of Luck!

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN I just saw that you are already assigned an issue, Once that issue is closed, I'll assign you this one.

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87 please assigned this issue to  me as issue #97 is closed!

**Comment by ekramzafar** [comment]
@singodiyashubham87 can you assigned me

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Assigned you the issue, Best of luck :)

**Comment by singodiyashubham87** [comment]
@ekramzafar This issue is already assigned, Kindly explore other issues or create new ones.

**Comment by AMISH-KHAN** [comment]
> @AMISH-KHAN Assigned you the issue, Best of luck :)
> 

Cool will start working on it soon

**Comment by AMISH-KHAN** [comment]
> @ekramzafar This issue is already assigned, Kindly explore other issues or create new ones.

Yeah sure let me just complete it first

**Comment by AMISH-KHAN** [comment]
is it fine? @singodiyashubham87 
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/fae15f97-dbf4-4b24-b8b1-abc09ba08e8f)

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN 2nd one is much better, You can go with it.

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87 please review PR #165
