### ISSUE TITLE
[FEAT] Saving designs on website itself or keeping it as a history

### ISSUE THREAD

**Issue by Chelseasingla1** [singodiyashubham87/Draw-it-out#123]
**Is your feature request related to a problem? Please describe.**
No option of saving design or going back to old designs.

**Describe the solution you'd like**
I would like to add a feature where one can save their designs or go back to their designs like keeping it as a history.

**Describe alternatives you've considered**

**Additional context**
Please assign me this issue under GSSoC'24.

**Comment by singodiyashubham87** [comment]
@Chelseasingla1 This feature is currentling being worked upon in issue #32.
Do you want to add something new? If yes then kindly explain.

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 This feature is currentling being worked upon in issue #32. Do you want to add something new? If yes then kindly explain.

@singodiyashubham87 i am not sure can you assign me a issue?

**Comment by singodiyashubham87** [comment]
@Chelseasingla1 You can find other open issues in the project or create other useful issues too.
Thanks for raising the issue.
