### ISSUE TITLE
[FEAT] Make an UPLOAD button

### ISSUE THREAD

**Issue by shravanibhor** [singodiyashubham87/Draw-it-out#127]
Making an upload button on the site such that the user can upload their own documents and start drawing on the same uploaded document.

**Comment by 0xabdulkhalid** [comment]
Your idea sounds great @shravanibhor!

I'm assigning this issue to you, If you stuck in between using images with Canvas then please do refer this [Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images) from MDN.

**Comment by 0xabdulkhalid** [comment]
Oops! @shravanibhor, A similar existing ISSUE have been found #87.

This one is a duplicate, So I'm closing this ISSUE.

Thank you!
