### ISSUE TITLE
[BUG]:breakpoint bug at 590px screen width

### ISSUE THREAD

**Issue by Stiffpixels** [singodiyashubham87/Draw-it-out#130]
**Describe the bug**
- The app is not responsive between 572-634px there is a margin right of 90% which can be removed without any problems
- buy me coffee button overlaps the hide and zoom buttons on tablet screens.

**To Reproduce**
1. Be on tablet screen between (572-634px)
2. Go to [draw it out](https://draw-it-out.vercel.app/)
3. See error

**Expected behavior**
The site should remain responsive and buy me coffee button should be relocated or hidden.

**Video: **

https://github.com/singodiyashubham87/Draw-it-out/assets/32983571/df7b202a-c683-4b48-810c-16f3418d79e3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by singodiyashubham87** [comment]
@Stiffpixels You should never create a PR before being assigned an issue.
I'm closing the previous PR, kindly create a new one after I assign you the issue. 
Best of Luck! :)

**Comment by Stiffpixels** [comment]
> @Stiffpixels You should never create a PR before being assigned an issue. I'm closing the previous PR, kindly create a new one after I assign you the issue. Best of Luck! :)

I never raised a PR in this repo

**Comment by singodiyashubham87** [comment]
@Stiffpixels My bad, Sorry & Keep contributing :)
