### ISSUE TITLE
[BUG] : Drawing screen Size

### ISSUE THREAD

**Issue by sivaprasath2004** [singodiyashubham87/Draw-it-out#132]
**Describe the bug**
- In the `+`  icon click the drawing window can be increase but the drawing the result can be hidden.
- In `-` icon click then the drawing window can be decrease the drawing the result can be transparent of the save image.

**To Reproduce**
1. Go to page 
2.  Draw the screen
3. Click on `+` icon
4. Click on `-` icon
4. See error in Draw window area

**Expected behavior**
- In the `+` click the screen can be increase the drawing doesn't erasing.

**Screenshots**

[Screencast from 2024-05-15 17-58-51.webm](https://github.com/singodiyashubham87/Draw-it-out/assets/121082414/0996dd08-666a-4da0-96a1-88f89291e788)

**Desktop (please complete the following information):**
 - OS:ubuntu
 - Browser: chrome

**Smartphone (please complete the following information):**
 - Device: Realme 8
 - OS: Android 12
 - Browser :chrome

**Comment by TomLucasakaTGeek** [comment]
@sivaprasath2004 assign this issue to me under GSSOC

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 Can you please add a recording of the issue you are facing as It's working fine on my end.

**Comment by 0xabdulkhalid** [comment]
@sivaprasath2004, Yeah you're right. You need to fix the distortion of drawing while increasing/decreasing height.

Instead of changing the height, the both options are just distorting the drawing.

I'm assigning this issue to you!

**Comment by sivaprasath2004** [comment]
@Sanj-bot already issue can be fixed. So I am closed the pull request.please another issue you can request....
