### ISSUE TITLE
[BUG]: Pen stroke button can be turned on while pen button is off

### ISSUE THREAD

**Issue by kumar1397** [singodiyashubham87/Draw-it-out#137]
**Describe the bug**
In the canvas page, the pen stroke button can be clicked and turned on while the pen button is off. Although we can not draw during this scenario, this creates a bad user experience.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'home page'
2. Turn off the pen button.
3. Turn on the pen stroke button.

**Expected behaviour**
The pen stroke button should be turned on only when the pen button is on. 

**Screenshots**
![Screenshot 2024-05-16 172310](https://github.com/singodiyashubham87/Draw-it-out/assets/122858524/8a24ab87-ba96-49d3-8612-dd1570002a2b)
![Screenshot 2024-05-16 172320](https://github.com/singodiyashubham87/Draw-it-out/assets/122858524/d7f83e03-5310-4cae-8308-fb5fbee355ad)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Microsoft Edge]

**Additional context**
Hello,
I think I can solve this problem . So, please assign me this problem under GSSoC '24.

**Comment by singodiyashubham87** [comment]
@kumar1397 Assigned you the issue, Best of Luck :)
