### ISSUE TITLE
There is no eraser option [FEAT]

### ISSUE THREAD

**Issue by Rohitha-pudu** [singodiyashubham87/Draw-it-out#140]
eraser option is not available,if wanted to delete whole board is being deleted,not able to delete a particular one

**Comment by 0xabdulkhalid** [comment]
Hi @Rohitha-pudu 👋🏻 

There's already an existing issue regarding adding Eraser feature, #36 

So I'm closing this issue, you can create a new issue (check existing ones before creating yours).
