### ISSUE TITLE
[FEAT]: Add Logo and Footer type section

### ISSUE THREAD

**Issue by rahul1841** [singodiyashubham87/Draw-it-out#141]
Is your feature request related to a problem? Please describe.
Missing logo and social media links.

Describe the solution 
There should be a logo at the top it will enhance user experience and add makes brand value of website,
and i can add footer type section in which we can add your social media links and all

Additional context
Every popular websites has their own logo and social media link section

**Comment by singodiyashubham87** [comment]
@rahul1841 There is a logo of the webapp and also the footer section is being worked upon in issue #62, If you wish to add some else then please elaborate.

**Comment by rahul1841** [comment]
@singodiyashubham87 
Generally if a person draws a sketch and makes slight mistake , the sketch has to be made again from the beginning.
So, best solution for this would be adding on eraser as a feature , or creating an undo button so that it can revert back to the previous change made.
we can even include redo button too.
Please assign this to me @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@rahul1841 This feature is also in progress under #32, Kindly read all opened issues first before creating new ones.
