### ISSUE TITLE
[BUG] The line drawn gets un centered from the cursor when drawing further downwards on the canvas.

### ISSUE THREAD

**Issue by Paper-Bag-dev** [singodiyashubham87/Draw-it-out#142]
**Describe the bug**

**To Reproduce**
1. Start drawing by pressing mouse down.
2. Drag the mouse while not releasing the mouse.
3. Let go of the mouse at end of canvas.
4. See the cursor move away from the end of the drawn line.

**Expected behavior**
The corresponding line should be drawn at the center of the cursor and should follow it accurately until the mouse pressed is left.

**Video**
https://github.com/singodiyashubham87/Draw-it-out/assets/92173476/df6cb58c-6d0f-4f55-ac53-cd0b8d818d8e

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave

**Comment by 0xabdulkhalid** [comment]
@singodiyashubham87, what you're thinking about this one?

**Comment by mondalsurojit** [comment]
Please assign me this issue under GSSoC'24. I have understood properly whats happening and I am very confident that I will find a way to solve this issue.

**Comment by singodiyashubham87** [comment]
@0xabdulkhalid Seems to be a genuine issue, I also faced it.

**Comment by singodiyashubham87** [comment]
@Paper-Bag-dev Assigned you the issue, Best of Luck :)

**Comment by singodiyashubham87** [comment]
@mondalsurojit Kindly explore other issues.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by 0xabdulkhalid** [comment]
This issue is now a Stale one, so you can assign any other willing contributors @singodiyashubham87.

**Comment by singodiyashubham87** [comment]
@mondalsurojit Want to work on the issue?

**Comment by mondalsurojit** [comment]
@singodiyashubham87 Please assign me this issue, I am free to work on this...

**Comment by singodiyashubham87** [comment]
@mondalsurojit Assigned you the issue, Good Luck :)

**Comment by mondalsurojit** [comment]
@singodiyashubham87 Can you please consider this PR as level 3....? As this bug took significant amount of time and efforts to solve...moreover it only got merged after solving the merge conflicts several times,  and after several reviews...Hope you understand :)

**Comment by singodiyashubham87** [comment]
@mondalsurojit I understand.

**Comment by mondalsurojit** [comment]
@singodiyashubham87 Thank you, Sir :)
