### ISSUE TITLE
Adding Light and Dark themes

### ISSUE THREAD

**Issue by Dhruv-Gaba** [singodiyashubham87/Draw-it-out#143]
**Is your feature request related to a problem? Please describe.**
Light and Dark themes can be incorporated in this project to make it more user friendly. Users will be able to switch between these themes according to their preferences making it more user oriented.

**Comment by 0xabdulkhalid** [comment]
Hi there @Dhruv-Gaba 👋🏻 

There's already an existing issue about adding Light/Dark theme #45, I encourage to create a new one which addresses any new change.

Since this one is a duplicate one, I'm closing this. Thank you!
