### ISSUE TITLE
[BUG] Color picker doesn't working 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [singodiyashubham87/Draw-it-out#144]
**Describe the bug**
Even after choosing a different color in the color picker  the color of the pen remains black .

**To Reproduce**
1. Go to website
2. choose any different color from the color picker 
3  The color of the pen won't change 

**Expected behavior**
The color of the pen must be change according to the color picker .
**Screenshots*

https://github.com/singodiyashubham87/Draw-it-out/assets/118350936/a1d090d1-0bf6-4f84-84a8-2bd77510a921

*

**Comment by singodiyashubham87** [comment]
@Ayushmaanagarwal1211 I have assigned you the issue, Best of Luck :)
