### ISSUE TITLE
Request for Addition of Eraser Feature

### ISSUE THREAD

**Issue by shaman-004** [singodiyashubham87/Draw-it-out#147]
In this current project, users lack the ability to erase mistakes easily, leading to frustration and inefficiency in editing tasks.

Solution:
We propose adding an eraser feature that allows users to easily remove unwanted content or annotations from their work. This eraser should be intuitive to use and seamlessly integrated into the editing interface.

Alternatives Considered:
Manual deletion: Users can currently manually delete content, but this process is cumbersome and prone to errors, especially in complex projects.

Additional Context:
The eraser feature would greatly enhance user experience and productivity, particularly in tasks requiring precise editing or correction of mistakes. It would streamline the editing process and improve overall project quality.

**Comment by soumya-maheshwari** [comment]
Hi @shaman-004 

There's already an existing issue regarding the Eraser feature, https://github.com/singodiyashubham87/Draw-it-out/issues/36

So I'm closing this issue for now, you can create a new issue.
