### ISSUE TITLE
[FEAT]: Making the website responsive 

### ISSUE THREAD

**Issue by samarpitadas** [singodiyashubham87/Draw-it-out#152]
The upper part of the website doesn't look good on my tablet screen. Screenshot is provided below how it looks.

I would like to make this website responsive using Tailwind CSS classes. @singodiyashubham87 please assign me this issue.

![Screenshot_2024-05-17-23-10-29-484](https://github.com/singodiyashubham87/Draw-it-out/assets/162856568/aaf5d039-4d90-4a44-b26b-b51dca1d7470)

**Comment by Harshitazz** [comment]
i want to work on this too

**Comment by singodiyashubham87** [comment]
@Harshitazz This issue is already assigned to someone else, Kindly explore other issues.

**Comment by singodiyashubham87** [comment]
@samarpitadas  Are you working on the issue ?

**Comment by singodiyashubham87** [comment]
I am unassigning due to inactivity.

**Comment by Skb08** [comment]
@singodiyashubham87 If no one is currently working on this, could you please assign it to me?
