### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [singodiyashubham87/Draw-it-out#155]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by singodiyashubham87** [comment]
@suhanipaliwal Thanks for raising the issue but there is already a PR template for the repository. Kindly explore other issues or raise new ones.
