### ISSUE TITLE
Text change in the last tutorial card

### ISSUE THREAD

**Issue by ayush-848** [singodiyashubham87/Draw-it-out#158]
**Is your feature request related to a problem? Please describe.**
The last tutorial card says Last.

**Describe the solution you'd like**
I will change the 'Last' to 'Start'

**Describe alternatives you've considered**
In addition if you permit I would like to add hover effects to the tutorial button, 'Skip' 'Next' 'Back'

**Additional context**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/126975547/2251c970-ed0e-46d8-a47f-b62dca0a39d3)

**Comment by ayush-848** [comment]
@singodiyashubham87 This is my first time participating in GSSoC, I would like you to assign this issue to me as I am participating in GSSoC'24 as a contributor.

**Comment by singodiyashubham87** [comment]
@ayush-848 I've assigned the issue to you, You may proceed now.
Best of Luck :)

**Comment by ayush-848** [comment]
@singodiyashubham87 I am not able to find this specific part in the code

**Comment by ayush-848** [comment]
@singodiyashubham87 I have done the PR, I have installed the lastest Vite version and I have changed the last button to Start

**Comment by ayush-848** [comment]
@singodiyashubham87 thanks for guiding me

**Comment by ayush-848** [comment]
Btw @singodiyashubham87 will this be considered as a level 1 PR?

**Comment by ayush-848** [comment]
@singodiyashubham87 please assign labels to the Merge
