### ISSUE TITLE
[BUG] : Multiple bot options instead of one

### ISSUE THREAD

**Issue by Prithwi32** [singodiyashubham87/Draw-it-out#161]
**Describe the bug**
After clicking to change thickness and color picker, canvas is getting cleared. we need to stop canvas get cleared.

**To Reproduce**
1. Draw something on canvas
2. Click on 'thickness / color picker'

**Expected behavior**
Canvas should have previous drawings, even after changing brush thickness and color

**Desktop (please complete the following information):**

**Comment by Prithwi32** [comment]
@singodiyashubham87 I noticed that this behaviour currently erased or overridden by PRs, so I would I like to get in to it and resolve this issue
Please could you assign me this issue

**Comment by singodiyashubham87** [comment]
@Prithwi32 Can you add a video of that?

**Comment by Prithwi32** [comment]
https://github.com/singodiyashubham87/Draw-it-out/assets/115262737/130419d5-17b4-46fa-b571-eaebd163f847

@singodiyashubham87  check out issue

**Comment by singodiyashubham87** [comment]
@Prithwi32 Video not playing, send on discord.
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/93720428/5e4b0bcc-4604-4410-bf64-7e0b3a37e986)

**Comment by singodiyashubham87** [comment]
@Prithwi32 Assigned! Best of Luck :)

**Comment by singodiyashubham87** [comment]
@Prithwi32 I've modified the issue, Best of Luck!

**Comment by Prithwi32** [comment]
> @Prithwi32 I've modified the issue, Best of Luck!

ok thank you :)
