### ISSUE TITLE
[BUG] Dark theme not working

### ISSUE THREAD

**Issue by AMISH-KHAN** [singodiyashubham87/Draw-it-out#166]
**Describe the bug**

when we click on the dark theme button it is applied only on some components but the background still remains gray.

**To Reproduce**
1. Go to website
2. Click on Moon button (dark theme button)
4. See error only some components changes color

**Expected behavior**

There should be a proper dark theme

**Screenshots**

https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/d9932771-d20e-4898-a737-e0c7a49ef500

**Additional context**

please assign this issue to me under GSSoC and add necessary labels

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Assigned!
Best of Luck :)

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87  please review PR #182
