### ISSUE TITLE
[FEAT] Improve UI by re-positioning the drawing canvas.

### ISSUE THREAD

**Issue by AnandK-pm** [singodiyashubham87/Draw-it-out#168]
**Is your feature request related to a problem? Please describe.**

Currently ,for the full visibility of drawing board , the user might need to scroll down . I intend to improve this by positioning the drawing canvas in the initial visible area of the webpage, ensuring it is immediately visible without any need for scrolling.

**Describe the solution you'd like**

I intend to realign  the drawing canvas by reducing the size of other features like menu bar.

![Screenshot 2024-05-20 004647](https://github.com/singodiyashubham87/Draw-it-out/assets/142206618/c7f5c20a-849d-4243-9a34-1a4d6a2834ae)

**Comment by singodiyashubham87** [comment]
@AnandK-pm Assigned you the issue, Best of Luck :)
