### ISSUE TITLE
[BUG] Unresponsive Menu Component

### ISSUE THREAD

**Issue by The-Phoenics** [singodiyashubham87/Draw-it-out#169]
**Describe the bug**
Currently the Menu component behaves not as expected, with window resize.

**To Reproduce**
1. Go to website
2. Resize the page
3. Notice the menu bar

**Expected behavior**
Menu component should adapt to the screen size and should not break its child nodes alignment.
This could be done by fixing the styling for the adjacent eye & theme button. And adding reponsiveness to the Menu component! 

**Screenshots**
![first](https://github.com/singodiyashubham87/Draw-it-out/assets/96228962/41c01a40-400d-47f1-97d6-083dbcde80bb)
![second](https://github.com/singodiyashubham87/Draw-it-out/assets/96228962/de01d1cc-12cc-4434-8fd8-3425ff80a55d)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Chrome]

Hey @singodiyashubham87, I would like to work on this to for GSSoC'24. This would improve the User Experience and make application look better and easy to use.

**Comment by singodiyashubham87** [comment]
@The-Phoenics How will you approach to resolve the issue?

**Comment by The-Phoenics** [comment]
Taking some inspiration from [excalidraw](https://excalidraw.com/), the current menu bar can be changed to a icon-only based tool bar with dropdowns. I will make the layout responsive for all the screen sizes.
Somewhat similar to this:
![excalidraw](https://github.com/singodiyashubham87/Draw-it-out/assets/96228962/ab21225d-3eb4-4099-b646-2aaf23e61f51)

which could be achieved with `position: absolute/sticky` & `flex` css styling.
I would appreciate your feedback on this idea, @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@The-Phoenics Fair enough, Assigned you the issue, Best of Luck :)
