### ISSUE TITLE
[FEAT] Separating Shape buttons 

### ISSUE THREAD

**Issue by AMISH-KHAN** [singodiyashubham87/Draw-it-out#170]
**Is your feature request related to a problem? Please describe.**

Currently the Shape button has circle rectangle and triangle shape combined.

![Screenshot 2024-05-20 170329](https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/cd1d004a-0f55-476f-a5da-4e649543e227)

**Describe the solution you'd like**

It would be good if we had separate Buttons.

**Additional context**

Please assign this issue to me under Gssoc

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN You are already assigned an issue, wait till that issue is closed. Then I'll assign you this issue if none has asked to work upon till then.

**Comment by AMISH-KHAN** [comment]
Cool

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87 I think now I don't have any assigned issue so please assign this one to me

**Comment by AMISH-KHAN** [comment]
hey @singodiyashubham87 can you please make it level 2 because I will be implementing something like we have for pencil i.e dropdown menu

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN As of level2, The issues are labelled considering many factors like approx. time, difficulty & priority.
& considering all those this issue was of easy type & therefore can't make it a level2 issue.
Hope you understand :)

**Comment by AMISH-KHAN** [comment]
Cool I will do it

**Comment by AMISH-KHAN** [comment]
> @AMISH-KHAN As of level2, The issues are labelled considering many factors like approx. time, difficulty & priority.
> & considering all those this issue was of easy type & therefore can't make it a level2 issue.
> Hope you understand :)

No problem 😁

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87 please check pr #210
