### ISSUE TITLE
[DOCS] Adding description about Shapes

### ISSUE THREAD

**Issue by AMISH-KHAN** [singodiyashubham87/Draw-it-out#171]
In the features section there should also be a description about shape

![Screenshot 2024-05-20 170803](https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/3c6a0eca-9ce2-4ece-b1bd-40aa31d8efbe)

**Comment by 2305e3ish** [comment]
I am confident i can get this done to improve description of project.Please assign this to me under GSSoC'24.

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87 Please look into this issue

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN You are already assigned #170 & that issue is still open, can't assign you multiple issues at the same time.

**Comment by ahinagangopadhyay** [comment]
@singodiyashubham87 I would like to work on this issue and modify the readme file to include details about the shapes.Please assign me this issue under GSSOC'24

**Comment by singodiyashubham87** [comment]
@ahinagangopadhyay Assigned, Best of Luck :)
