### ISSUE TITLE
[BUG]: Remove cross and add Clear button

### ISSUE THREAD

**Issue by Saimanjari777** [singodiyashubham87/Draw-it-out#178]
**Describe the bug**
The cross button to clear the canvas is not appropriate. I wan to add the clear button instead of cross button.

**Expected behavior**
The clear button makes it easy for the users to understand.

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/130165687/df0e98b6-f9e1-4a8e-b5e9-8acaedc94845)

**Additional context**
I am working under GSSoC'24 
Please assign this task to me @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@Saimanjari777 I don't think so, The button with cross check-mark looks clean, We don't need to change it.
Thanks for raising the issue.
