### ISSUE TITLE
Chat bot issue in the webapp

### ISSUE THREAD

**Issue by Sowmyatiwari** [singodiyashubham87/Draw-it-out#180]
**Describe the bug**
There is an issue in the chatbot of this webapp , it is giving repeated responses for a given single prompt.

**To Reproduce**
1. Go to ' the website "Draw it out"
2. Click on the drawbot feature
3.Give some prompts to the drawbot (it gives double responses for any given prompt).

**Expected behavior**
Only one response should be given to one given  prompt.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows NT 
 - Browser "chrome

**Additional context**
I would like to work on this issue , so that it gives a single response for the given prompt , as it will be crystal clear for the website user to use.
![chatbotissue](https://github.com/singodiyashubham87/Draw-it-out/assets/133684872/b79e0eec-328e-42e8-bda0-4c19b68fb58b)
![chatbotissue](https://github.com/singodiyashubham87/Draw-it-out/assets/133684872/400896a5-8e9c-483b-9c46-78380b4c83b1)

**Comment by singodiyashubham87** [comment]
@Sowmyatiwari Assigned! Best of Luck :)

**Comment by Sowmyatiwari** [comment]
Thank you @singodiyashubham87 , I will start working on this.

**Comment by singodiyashubham87** [comment]
@Sowmyatiwari Any updates?

**Comment by singodiyashubham87** [comment]
@Sowmyatiwari Okay then, I'm closing this issue.
