### ISSUE TITLE
[BUG] Unclear which shape is selected

### ISSUE THREAD

**Issue by vaibhavityagi** [singodiyashubham87/Draw-it-out#181]
**Describe the bug**

**To Reproduce**
1. Go to the website
2. Start drawing
3. Select a shape
4. You can't see which shape you are currently as it is not highlighted in the panel

**Expected behavior**
The shape that you are currently using should be highlighted in the panel

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/78082871/008bd3bc-394c-4520-a45a-0d2cda73335c)

**Desktop**
 - OS: Windows
 - Browser: Brave

**Comment by vaibhavityagi** [comment]
@singodiyashubham87 please assign this issue to me under GSSOC24

**Comment by AMISH-KHAN** [comment]
hey @vaibhavityagi I have already raised a similar issue #170

**Comment by 0xabdulkhalid** [comment]
Hi there @vaibhavityagi 👋🏻 

You're assigned, Create a PR once you made the right changes and don't forget to test your changes before creating a PR!

**Comment by 0xabdulkhalid** [comment]
Hi there @vaibhavityagi 👋🏻, There's already an issue to address similar bug.

So I'm closing this issue, you can create a New one addressing any other changes. Thank you!
