### ISSUE TITLE
[BUG]: Pen Drawing not working after selecting Shapes

### ISSUE THREAD

**Issue by Prithwi32** [singodiyashubham87/Draw-it-out#188]
**Describe the bug**
unable to write with pen after we select shapes, even after clicking on pen leads to drawing of previous selected shape only.

**To Reproduce**
1. Go to 'website'
2. Click on 'pen' and draw
3. Now select any 'Shape' use it
4. Now again try to use pen
5. See error

**Expected behavior**
Pen features not lost even after selecting other shapes to draw.

**Screenshots**

https://github.com/singodiyashubham87/Draw-it-out/assets/115262737/3d812c57-aa0e-4f13-9bdf-70336a2ec061

**Desktop (please complete the following information):**
 -OS : Windows
-Browser: MicrosoftEdge

**Comment by singodiyashubham87** [comment]
@Prithwi32 Assigned you the issue, Best of Luck :)

**Comment by singodiyashubham87** [comment]
@Prithwi32 Any updates?

**Comment by Prithwi32** [comment]
> @Prithwi32 Any updates?

@singodiyashubham87 hello...I will do that is soon...
I was busy with hackthon

**Comment by singodiyashubham87** [comment]
@Prithwi32 Try to resolve it ASAP or else tell me, and I'll assign it to the next interested contributor.

**Comment by Prithwi32** [comment]
> @Prithwi32 Try to resolve it ASAP or else tell me, and I'll assign it to the next interested contributor.

Okay sure
.... sorry for delay 🥲

**Comment by Prithwi32** [comment]
> > @Prithwi32 Try to resolve it ASAP or else tell me, and I'll assign it to the next interested contributor.
> 
> Okay sure .... sorry for delay 🥲

I will complete by next 2days

**Comment by singodiyashubham87** [comment]
@Prithwi32 Good Luck :)

**Comment by Prithwi32** [comment]
@singodiyashubham87 made PR check it out..Thank You!
