### ISSUE TITLE
[BUG]: Visibilty of Pen dropdown 

### ISSUE THREAD

**Issue by AMANVISHWAKARMA27** [singodiyashubham87/Draw-it-out#189]
**Describe the bug**
Visibility of pen is less in dark mode. It is irritating and can be made more attractive.

**To Reproduce**

**Expected behavior**
In darkmode, the dropdown's color is very light.  Some different color code should be used.

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/143862235/7a59221a-420f-49a8-b35a-8c31f2858324)

@singodiyashubham87 , kindly assign the issue to me.

**Comment by singodiyashubham87** [comment]
@AMANVISHWAKARMA27 Kindly resolve the issue which you are already assigned then only we can assign you this issue if no one else has asked to assign before that.

**Comment by Yashaswale** [comment]
@AMANVISHWAKARMA27  I would like to work on this issue

**Comment by Utsavladia** [comment]
Dear @singodiyashubham87 ,
I also observed this issue and would like to fix it.
I belive I can make it a good experience for the users with fixing this issue along with other in UI like selecting the shape should have seperate hover effect instead of highlighting the whole section of shapes.


Kindly give me the opportunity to fix these and enhance the experience of users.

**Comment by singodiyashubham87** [comment]
@Utsavladia I appreciate your zeal to contribute but as Yash asked before you & according to the FIFO policy he deserves the issue to be assigned, Do explore other issues :)

**Comment by singodiyashubham87** [comment]
@Yashaswale Any updates?

**Comment by Utsavladia** [comment]
@singodiyashubham87 
You can assign this to me...
I can work on this issue if no response is there 😊

**Comment by singodiyashubham87** [comment]
Reassigning due to inactivity.

**Comment by singodiyashubham87** [comment]
@Utsavladia Best of Luck :)

**Comment by Utsavladia** [comment]
@singodiyashubham87 
Thankyou 
I'll fix it asap
