### ISSUE TITLE
[FEAT] alignment needs to be done in multiple color section 

### ISSUE THREAD

**Issue by kapilG0** [singodiyashubham87/Draw-it-out#194]
**Is your feature request related to a problem? Please describe.**
![Screenshot_20240523_102313](https://github.com/singodiyashubham87/Draw-it-out/assets/59639410/13de2d59-c255-45da-aefb-bc9c4781a520)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kapilG0** [comment]
Hello @singodiyashubham87 please assign this issue to me under gssoc 24

**Comment by singodiyashubham87** [comment]
@kapilG0 Do provide a recording, because it's showing fine on my side.

**Comment by singodiyashubham87** [comment]
@kapilG0 Yes, please share a recording, that will be better.

**Comment by singodiyashubham87** [comment]
@kapilG0 Assigned you the issue, Best of Luck :)

**Comment by kapilG0** [comment]
Hello @singodiyashubham87 . i have raised pr #235 . please check
