### ISSUE TITLE
[FEAT] avatar not loading in draw bot

### ISSUE THREAD

**Issue by kapilG0** [singodiyashubham87/Draw-it-out#195]
**Is your feature request related to a problem? Please describe.**
![Screenshot_20240523_102522](https://github.com/singodiyashubham87/Draw-it-out/assets/59639410/b9fe6249-99a1-43a4-bea8-7014d3c19f9b)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by singodiyashubham87** [comment]
@kapilG0 Duplicate of #192
