### ISSUE TITLE
[BUG] Enhance the overall UI of the website

### ISSUE THREAD

**Issue by mohangolakoti** [singodiyashubham87/Draw-it-out#196]
**Describe the bug**
Hello @singodiyashubham87,

The overall UI of the website is not looking effective. The color palette and the design need improvements. Please assign me this issue so I can make the necessary changes to enhance the UI and overall visual appeal.

**Comment by singodiyashubham87** [comment]
@mohangolakoti An issue can't be generic, be specific what exact thing will you change in the UI to make it look better, & if possible show a prototype so that we can have a look & if that prototype looks appealing then I'll assign you the issue to work.

**Comment by lakshayrao3114** [comment]
Hello @singodiyashubham87 

My name is Lakshay Rao and I'm a contributor under GSSOC'24.

I think using some other font family( something not very fancy but one that can be relatable to how people write on digital screens that looks like pen strokes) could enhance the visual appeal of the whiteboard ...If you dont like this one I could work on some other font to figure out something better.

Please assign me this issue under GSSOC'24 .
![Screenshot 2024-05-23 173253](https://github.com/singodiyashubham87/Draw-it-out/assets/97534058/4657aee2-e039-4eee-8061-99337961ffcf)

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
