### ISSUE TITLE
Use of another cursor type 

### ISSUE THREAD

**Issue by lakshayrao3114** [singodiyashubham87/Draw-it-out#199]
Hi @singodiyashubham87 
My name is Lakshay Rao and I'm a contributor in GSSOC'24.

I would like to make the following updates to the project :- 
Instead of using the crosshair cursor on the white board , we can make use of a pen-tip type cursor or a cursor in the form of a chalk (whichever looks more suited) to match the look and feel of the board to a real-life whiteboard .

Please assign me this task under GSSOC'24

Thanks In Advance!!

**Comment by soumya-maheshwari** [comment]
Hello @lakshayrao3114 
could you please provide a prototype or screenshots showcasing how the new cursor would look?

**Comment by HimangshuRanjan** [comment]
@singodiyashubham87, I would like to fix this issue. Please do assign me this under GSSOC'24.

**Comment by singodiyashubham87** [comment]
@HimangshuRanjan Kindly provide a screenshot of how the cursor will look.

**Comment by yasaswi-2204** [comment]
Dear @singodiyashubham87 
Please assign me this issue
I will change the curser style to a better one ( for example grab )
I have expertise in HTML and CSS

**Comment by singodiyashubham87** [comment]
@yasaswi-2204 I do not doubt your expertise but I can't assign you the issue before you show me the prototype of the cursor.
& As of grab one, that won't look good while drawing that is used while dragging elements, I hope you know that :)

**Comment by yasaswi-2204** [comment]
Dear @singodiyashubham87, Thanks for the consideration of my comment, if not grab; then I can change the cursor style(while drawing on the board) to a pointer. I know that it looks basic, but I believe it's better than the crosshair style.
I request you to please assign me this issue under gssoc label
Thank you

**Comment by singodiyashubham87** [comment]
@yasaswi-2204 Assigned, Best of Luck :)

**Comment by yasaswi-2204** [comment]
Dear PA,

I created the pull request and pushed it. Please check and merge it

Thank you

**Comment by yasaswi-2204** [comment]
Dear PA,

My PR is merged, but I didn't get the score for it. Can you please tell me
what is the reason for this.

Thank you

**Comment by yasaswi-2204** [comment]
Dear PA,

Please add the level number for my PR, so that the score will be added.

Thank you
