### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by sanjay-kv** [singodiyashubham87/Draw-it-out#20]
Learn repos should have a LEARN.md file to teachstudent how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by singodiyashubham87** [comment]
@sanjay-kv I've created a PR for this issue, Kindly check it out.

**Comment by sanjay-kv** [comment]
I have reviewed the file, all good to go. you can merge and close the issue #26
