### ISSUE TITLE
[BUG] : Resposive Missing

### ISSUE THREAD

**Issue by sivaprasath2004** [singodiyashubham87/Draw-it-out#201]
Hello @singodiyashubham87 ,
**Describe the bug**
- In this project doesn't responsible for the `mobile` site. 

**To Reproduce**
1. Go to site
2. Click on `Inspect`
3. switch to `mobile` site

**Expected behavior**
- In `mobile` and  all devices can be proper responsive every user can be expecting but didn't work..

**Screenshots**

[Screencast from 2024-05-24 19-05-04.webm](https://github.com/singodiyashubham87/Draw-it-out/assets/121082414/bfc3dcb2-827c-4f58-a9c0-6724560603e1)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device: Realme 8
 - OS: Android
 - Browser: chrome

**Comment by hunxjunedo** [comment]
requesting assignment, would love to contribute if the repo is open to external contributions.

**Comment by 0xabdulkhalid** [comment]
Hi there @sivaprasath2004 👋🏻, could you wait for a moment. Because some PR's already addressing this issue.

If they not fixed this then you can be assigned for this issue. Thank you!

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 Want to work on the issue now?

**Comment by sivaprasath2004** [comment]
@singodiyashubham87 I want to work

**Comment by 0xabdulkhalid** [comment]
You're assigned @sivaprasath2004

PS: Don't create PR unless you're assigned to it's corresponding issue, your PR can be rejected if you do so. Hope you understood.
