### ISSUE TITLE
[FEAT]we can add (+) menu or (-) menu as we increase or decrease thickness.

### ISSUE THREAD

**Issue by shivamqums7482** [singodiyashubham87/Draw-it-out#204]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by singodiyashubham87** [comment]
@shivamqums7482 What's the need of "+" & "-"? We already have a range option & I think that's enough.
Kindly explore other issues :)
