### ISSUE TITLE
Padding Issue

### ISSUE THREAD

**Issue by AYUSHMAN777** [singodiyashubham87/Draw-it-out#205]
![Screenshot (266)](https://github.com/singodiyashubham87/Draw-it-out/assets/110350591/f43c69b5-23a6-4df2-b2eb-189f697f60a8)
Padding between the comment box and message logo is not sufficient.

**Comment by singodiyashubham87** [comment]
@AYUSHMAN777 The screenshot you provided is of open zone project(which is a different webapp) & this one is "Draw-it-out", Be conscious while creating issues.
