### ISSUE TITLE
Visibility Issue in Dark Mode

### ISSUE THREAD

**Issue by 18Venus** [singodiyashubham87/Draw-it-out#207]
*Describe the bug*
Guidelines are not visible in dark mode. The text and background color seem to be overlapping.

*To Reproduce*
1. Go to the site.
2. Click on dark mode ('Half Moon' icon) (if the icon is 'Sun' you are already in dark mode)
3. Click on the 'book' icon on the leftmost top.
4. A text area will appear which will have visibility issues.

*Expected behavior*
The guideline box that appears has the same/ very close color for text and background making it very difficult to read. 
Rather the background should be darker and text of the same color to adhere with the dark mode.

*Screenshots*
![GSSOC Issue1](https://github.com/singodiyashubham87/Draw-it-out/assets/149051659/e1811ad4-710c-4511-8864-2b4b3394ddd7)
![WhatsApp Image 2024-05-25 at 12 11 05_ef0529bd](https://github.com/singodiyashubham87/Draw-it-out/assets/149051659/dce63bea-afc2-4ce7-ad5b-d904181892c0)

*Desktop:*
 - OS: Windows
 - Browser: Bing, Chrome

*Smartphone:*
 - Device: Samsung A14
 - OS: Android
 - Browser : Chrome

**Comment by Utsavladia** [comment]
Dear @singodiyashubham87,

I understand the issue and am confident I can address it effectively. I request that you assign this issue to me under GSSOC '24.
I have extensive experience working on projects with dark and light mode options and I will also improve the UI of this guidelines section for better responsiveness and user experience.

Hope you will consider my request.
Thank you.

**Comment by singodiyashubham87** [comment]
@18Venus Do you want to work on the issue?
@Utsavladia If the issue raiser declines to take up the issue, then I'll assign it to you.

**Comment by 18Venus** [comment]
Hey @singodiyashubham87, yes I do want to work on the issue under GSSOC'24. Thank you!

**Comment by singodiyashubham87** [comment]
@18Venus Assigned, Best of Luck :)
