### ISSUE TITLE
Visiblity while selecting a pencil, shape and all other hover effects

### ISSUE THREAD

**Issue by Utsavladia** [singodiyashubham87/Draw-it-out#208]
I felt frustrated when we select a shape among square circle and trianlgle It don't have good UI to select one of them 
we don't get the shape highlighed only the one we are selecting and all three gets highlighted on hover.

Also on selecting the pencil the options in dropdown have color similar to background which make it less visible.

I will improve the UI on hover of this and the section of selecting the pencil.
![Screenshot 2024-05-25 152718](https://github.com/singodiyashubham87/Draw-it-out/assets/124615886/2dc7703a-b1d0-4cb7-af42-4f80b809b754)

**Comment by 0xabdulkhalid** [comment]
Hi there @Utsavladia 👋🏻, there's already an issue exists similar to yours #189.

So I'm closing this one, you can create a New issue for any other changes. Thank you!
