### ISSUE TITLE
[BUG:] Increase Height Button is Not Working

### ISSUE THREAD

**Issue by SrinivasDevolper** [singodiyashubham87/Draw-it-out#211]
**Describe the bug**
 Increase Height Button is Not Working

**Expected behavior**
I Fix Increase Height Button to Increase the sketch board

**Screenshots**

https://github.com/singodiyashubham87/Draw-it-out/assets/121508628/897cfe2f-eada-437f-bdea-662f03b3cee1

**I am GSSOC24 Contributor
Please assign this issue, I would like to work on this issue**

**Additional context**

**Comment by singodiyashubham87** [comment]
@SrinivasDevolper Add a recording as the button is working when I tried.

**Comment by SrinivasDevolper** [comment]
When you repeatedly click the Decrease Height button until the size of the sketchboard is reduced to an invisible extent, the Increase Height button does not work. once you try out again

**Comment by singodiyashubham87** [comment]
@SrinivasDevolper Assigned you the issue, Best of Luck :)
