### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [singodiyashubham87/Draw-it-out#214]
### Currently, there is an issue template for this repo, but no issue form which will help users in contributing.

- #### I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
#### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/73957207/b7ba454d-94f8-4869-83f5-5263fb5f98c2)

- and issue templates:

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/73957207/048543bf-5090-4a75-bbb2-cbf29d6dc5b4)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by singodiyashubham87** [comment]
@TonyStark-47 & How will you implement this?

**Comment by TonyStark-47** [comment]
@singodiyashubham87, by adding .yml file like bug_report.yml instead of bug_report.md to the ISSUE_TEMPLATE in .github file.
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/73957207/aae4a6ca-8c86-410b-b0ea-d3b732570003)

**Comment by singodiyashubham87** [comment]
@TonyStark-47 Assigned you the issue, Best of Luck :)

**Comment by TonyStark-47** [comment]
Hey @singodiyashubham87, I have raised a PR #292 related to this issue. Please check it out.
