### ISSUE TITLE
[BUG] Background changing panel breaking layout

### ISSUE THREAD

**Issue by The-Phoenics** [singodiyashubham87/Draw-it-out#215]
**Describe the bug**
Unresponsive background colour changing panel on left

**To Reproduce**
1. Go to 'website'
2. Resize width of application
3. Observer left side bg-color changing panel breaking out of the layout.

**Expected behavior**
The left panel should be fixed at left side. This could be achieved with make its position `relative` or `fixed` in CSS. And making it fit with the other sections of the layout.

**Screenshots**
![333566115-b2735587-cba8-48a9-b83c-b4d573232f71.png](https://github.com/singodiyashubham87/Draw-it-out/assets/96228962/1bb0aae4-179c-4fd4-9f89-9dd205db2a03)

![333565906-c433fcef-6a55-4033-85ea-c5517c28283e.png](https://github.com/singodiyashubham87/Draw-it-out/assets/96228962/16f9f677-6f01-4f22-8465-5b0d4e2058c1)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Chrome]

I'd like to work on this for GSSoC'24.

**Comment by The-Phoenics** [comment]
Hey @singodiyashubham87,
Can you assign this to me?

**Comment by singodiyashubham87** [comment]
@The-Phoenics Sorry for the delay, was a little bit busy with exams & other stuff.
There is already an open issue regarding responsiveness, can you specify what unique you want to fix?

**Comment by The-Phoenics** [comment]
I would like to propose this new changes to UI, fixing the `BgColorChanger` component to the left-most with a fix width. And create a toggle for smaller screen sizes. @singodiyashubham87
![design](https://github.com/singodiyashubham87/Draw-it-out/assets/96228962/1b66528d-e717-4c96-a512-1dc73c9431eb)

**Comment by The-Phoenics** [comment]
Hey  I would like to propose these changes to UI, we can fix the `BgColorChanger` to the left with a fixed width.
And add a toggle for it at smaller screen sizes @singodiyashubham87.
![design](https://github.com/singodiyashubham87/Draw-it-out/assets/96228962/393c6397-5e3b-4b27-90af-bd02f10ddd83)

**Comment by The-Phoenics** [comment]
Hey @0xabdulkhalid
Can you take a look at this issue and assign me if it seems a valid proposal?

**Comment by 0xabdulkhalid** [comment]
Yeah sure @The-Phoenics, this issue seems to be valid proposal which must need to be addressed.

I'm assigning this issue to you, Create a PR once you tested your changes on local.

Good luck!
