### ISSUE TITLE
[BUG] Improper Scroll Behaviour

### ISSUE THREAD

**Issue by Chetan8299** [singodiyashubham87/Draw-it-out#220]
**Describe the bug**
When we first open the site it gives us cues on how to get started but the at the second cue it should be readable but it hides due to improper 

**To Reproduce**
1. Go to the Website
2. Click on next 
3. After that you can see that the text instructions get hidden due to improper scolling

**Expected behavior**
The scrollbar should automatically be at the right position as soon as we hit the next key.

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/167693543/86aa8b62-d2eb-414e-936d-da15ee234cee)

**Desktop (please complete the following information):**
 - Windows
 - Google Chrome

**Comment by singodiyashubham87** [comment]
@Chetan8299 Assigned you the issue, Best of Luck :)
