### ISSUE TITLE
[BUG]:designing part with perfect layout

### ISSUE THREAD

**Issue by Varsani2520** [singodiyashubham87/Draw-it-out#221]
**Describe the bug**
here section content is not in perfect layout as well as icon ,font size...
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/137641079/11cc627d-03a7-4f1a-b500-d9dca7d074cc)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Varsani2520** [comment]
Hey @singodiyashubham87 ,assign this issue

**Comment by singodiyashubham87** [comment]
Invalid!
