### ISSUE TITLE
[BUG] Footer Bug, related to buttons

### ISSUE THREAD

**Issue by tarushi29** [singodiyashubham87/Draw-it-out#226]
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/128239884/8ef6c23b-c0e3-4c16-bd24-647cdbc6793a)
These buttons when clicked should provide suitable information or direct user to another page.

**Comment by singodiyashubham87** [comment]
@tarushi29 You are right, what will you do when the buttons are clicked?

**Comment by tarushi29** [comment]
> @tarushi29 You are right, what will you do when the buttons are clicked?

Add these in components js folder where each page will be appropriately coded

**Comment by singodiyashubham87** [comment]
@tarushi29 No, We don't want these pages, It will be better if you can make a modal (pop-up) component which will tell the specific info to user.
Like on clicking About, a pop will open & there will be text about the app, same for our team.
For home button we don't have to do anything & for contact us, you can make it anchor tag with href="https://shubham-s-socials.vercel.app/", & they will get my contact details.

**Comment by INam1995** [comment]
@singodiyashubham87 
I can fix this issue as per your demand , can you please assign this issue to me under SSOC'24.
Thank you!

**Comment by tarushi29** [comment]
@singodiyashubham87  I will fix the issue as per your demand, please assign me.

**Comment by singodiyashubham87** [comment]
@tarushi29 Assigned you the issue, Best of Luck :)

**Comment by singodiyashubham87** [comment]
@INam1995 Explore other issues, this one is assigned to tarushi :)

**Comment by harsh02mishra** [comment]
@tarushi29 are you adding webpages in the footer buttons in this issue?

**Comment by singodiyashubham87** [comment]
Unassigning due to inactivity.

**Comment by Saipradyumnagoud** [comment]
@singodiyashubham87 please assign me the issue

**Comment by sakshii00** [comment]
@singodiyashubham87 I can work on half of the issue and half can be worked on by @Saipradyumnagoud if thats okay with you. Since there are 5 things in footer, some can be taken by me and some can be taken by him.

**Comment by singodiyashubham87** [comment]
@sakshii00 You must ask @Saipradyumnagoud first for that, if he agrees then only I can assign to you both otherwise I would have to assign to Sai only.

**Comment by singodiyashubham87** [comment]
@Saipradyumnagoud GSSOC, right?

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud GSSOC, right?

yes @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@Saipradyumnagoud Read the discussion above so that you will get an idea what you have to make.

**Comment by MoonStar05** [comment]
Can u assign this issue to me

**Comment by singodiyashubham87** [comment]
@MoonStar05 Sorry but this issue is already assigned to someone.

**Comment by sivaprasath2004** [comment]
@singodiyashubham87 If i implement to the `Contact us` page mail concept like `Thank you for Contacting Draw it out community` this is message send to the use please assign me ..
- I will make sure i will finish this issue within 1day ...

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 I'll tell you if that's needed, let this issue be resolved first.
