### ISSUE TITLE
[BUG]: guidelines icon  button 

### ISSUE THREAD

**Issue by Rupalpy** [singodiyashubham87/Draw-it-out#227]
when clicked on left side book icon , the guidelines appear to the right , which takes time to direct to the right side and also to close it we have to move from left to right
![Uploading Screenshot_20240529_143414.png…]()

**Comment by singodiyashubham87** [comment]
@Rupalpy Under which program you want to contribute SSOC or GSSOC?

**Comment by Rupalpy** [comment]
> @Rupalpy Under which program you want to contribute SSOC or GSSOC?
GSSOC
