### ISSUE TITLE
Add issues

### ISSUE THREAD

**Issue by sanjay-kv** [singodiyashubham87/Draw-it-out#23]
As the maintainer of a Collaborate repo, keeping Issues up-to-date will help the student community understand what they can do to contribute. Issues should vary by the easy (update documentation) to the difficult (add a new feature). The more involved you are, the more opportunities there are to collaborate.

Recommendations:

Add issues of varying difficulty to the repo often. you can add the tag GSSoC'24, good first issue etc.
Generate issues even if you plan on solving them, so the repository appears as active.
Contribute/commit often to the repo so it does not go stale.

Reference https://github.com/Recode-Hive/Stackoverflow-Analysis/issues

**Comment by singodiyashubham87** [comment]
@sanjay-kv I have created 6 new issues, I guess they are enough as of now.
Kindly have a look.

**Comment by sanjay-kv** [comment]
Yes Good enough. Closing this issue @singodiyashubham87
