### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by RushilJalal** [singodiyashubham87/Draw-it-out#230]
### Screenshots

Location : `src/components/Menu.jsx`

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/54212357/ccc7d637-0cd0-47f3-a4e3-a7b25cad788f)

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/54212357/a050b146-f80f-4b8a-aeea-c35ca4b45960)

Location : `src\utils\canvas.js`

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/54212357/40adc2c9-f358-4ffb-9d04-3ec05c55114d)

Location : `src\components\Footer.jsx`

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/54212357/f4404aa4-81fb-4d0c-b1ad-0a5361c722ce)

Kindly assign the issue to me🙏

**Comment by RushilJalal** [comment]
I also want to add titles to the menu buttons which don't have it already(draw shape, fill shape, thickness, download)
I will also fix titles like IncreaseHeight, DecreaseHeight which are method names rather than descriptions.

**Comment by singodiyashubham87** [comment]
@RushilJalal Under which program you want to contribute SSOC or GSSOC?

**Comment by RushilJalal** [comment]
> @RushilJalal Under which program you want to contribute SSOC or GSSOC?

SSOC

**Comment by singodiyashubham87** [comment]
@RushilJalal Assigned you the issue, Best of Luck :)
