### ISSUE TITLE
[FEAT] to add the feature of eraser 

### ISSUE THREAD

**Issue by suryapratapsingh26** [singodiyashubham87/Draw-it-out#233]
**Is your feature request related to a problem? Please describe.**
eraser feature is required for this project as during drawing if user want to delete if any mistakes happened

**Comment by suryapratapsingh26** [comment]
I am gssoc'24 participant i want to work on this feature . Assign me this

**Comment by singodiyashubham87** [comment]
@suryapratapsingh26 Duplicate of #36
