### ISSUE TITLE
[BUG] Icon not visible in dark mode

### ISSUE THREAD

**Issue by karthickkumarsm** [singodiyashubham87/Draw-it-out#236]
**Describe the bug**
Buy me coffee Icon not visible in dark mode and I like to work it under GSSoC'24

**To Reproduce**
switch to Dark mode

**Expected behavior**
The icon should be visible even in dark mode

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/89688112/ee1ccc48-0581-472e-a5e1-f5e79634ead7)

**Desktop (please complete the following information):**
 - OS:windows 11
 - Browser: Microsoft edge

**Comment by bhavanishanker-png** [comment]
please assign this issue to me, i can work on this, i have made the local setup as well, i can make the changes, and resolve this issue

**Comment by Monalisha-Roy** [comment]
hey @karthickkumarsm , please assign this issue to me.  I can fix this issue quickly and smoothly. I'd very much like to work on this issue. Please assign it to me.

**Comment by singodiyashubham87** [comment]
@karthickkumarsm Assigned you the issue, Best of Luck :)

**Comment by Shubhamsingh2110** [comment]
i would like to work on it #236@singodiyashubham87

**Comment by singodiyashubham87** [comment]
@karthickkumarsm Are you working on the issue?

**Comment by H1mang1** [comment]
@singodiyashubham87  please assign me this issue I can fix this quickly

**Comment by karthickkumarsm** [comment]
> @karthickkumarsm Are you working on the issue?

yes bro

**Comment by karthickkumarsm** [comment]
done bro
