### ISSUE TITLE
[FEAT]: Improving the UI related to color pallet

### ISSUE THREAD

**Issue by Harsh-KumarJha** [singodiyashubham87/Draw-it-out#237]
**Is your feature request related to a problem? Please describe.**
The color pallet for canvas that is stretched beyond the landing page can be annoying as to select the color at the bottom I need to scroll the page to select the color.

**Describe the solution you'd like**
It would be better to place in horizontally below the icon pallet to make it always visible while drawing while keeping it minimalist.

**Describe alternatives you've considered**

1. It can also be divided into 2 columns for better visibility . 
2. Or maybe a separate block where all colors can be beside the tools pallet.

**Additional context**
This will give the drawing canvas more room and be centered for better appeal. and the DrawBot wouldn't overlap it.

Before
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/121922047/10206166-f2a5-4223-bda5-778b19953e0a)

After the issue is resolved:
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/121922047/7a64aa25-0f92-4522-810d-05e12aa410ff)

Kindly assign this issue to me under GSSoC.

**Comment by ShrutiPriya13** [comment]
assign this to me

**Comment by singodiyashubham87** [comment]
@Harsh-KumarJha Assigned you the issue, Best of Luck :)
& position the color palette below the canvas not above.
