### ISSUE TITLE
Design improvement

### ISSUE THREAD

**Issue by SuryanshuKushwaha** [singodiyashubham87/Draw-it-out#239]
Need to centre and improve design of  contact us page , assign me this issue and label it under GSSOC @singodiyashubham87 

**Screenshots**
![Screenshot (43)](https://github.com/singodiyashubham87/Draw-it-out/assets/114632428/d04463fb-2f3c-4989-9c7d-c6f6974b4866)

**Comment by singodiyashubham87** [comment]
@SuryanshuKushwaha This is not Draw-it-out application's screenshot, it's of another project, be conscious while creating issues.
