### ISSUE TITLE
Add templates for issues

### ISSUE THREAD

**Issue by sanjay-kv** [singodiyashubham87/Draw-it-out#24]
Issue templates are very helpful for a collaboration repo. When users identify a bug or want to add a new feature, you can provide templates so you can collect all the pertinent information you need to fix a bug or add a new feature.

We recommend creating a “Report Bug” and “Feature Request” issue template.

Some suggested prompts/questions you can add to a “Report Bug” template are:

Briefly describe the bug
What is the expected behavior?
Please provide step by step instructions on how to reproduce the bug
Some suggested prompts/questions you can add to a “Feature Request” issue template are:

Briefly describe your feature request
What problem is this feature trying to solve?
How do we know when the feature is complete?

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/issues/new/choose
Click on Get Started button and copy the template to yours.

**Comment by singodiyashubham87** [comment]
@sanjay-kv Kindly check the associated PR. So that we can proceed.

**Comment by sanjay-kv** [comment]
#27 Needs revision. Kindly check the review comments

**Comment by singodiyashubham87** [comment]
@sanjay-kv I followed the guide and created a new PR, the issue templates are generating as markdown files only but in the ".github" directory which, after merging will be added to the templates for the issues.
Kindly have a look.

**Comment by sanjay-kv** [comment]
Yes @singodiyashubham87 Sorry for the confusion. I marked it done. Thanks
