### ISSUE TITLE
[BUG]Color Pallete for Drawing pad not working properly

### ISSUE THREAD

**Issue by aaryancodeshere** [singodiyashubham87/Draw-it-out#240]
**Describe the bug**
The color pallete for choosing the color fo drawing pad in not working properly. It should be corrected.
**To Reproduce**
1. Go to Home page
2. Click on 'Color pallete
3. See error

**Expected behavior**
color of drawing pad should change as we change color in color pallete.

**Screenshots**

<img width="1401" alt="Screenshot 2024-05-30 at 9 32 01 PM" src="https://github.com/singodiyashubham87/Draw-it-out/assets/124273822/cb2d8e2b-0ed3-4d82-a18c-a39e16385f75">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome

**Comment by singodiyashubham87** [comment]
@aaryancodeshere Duplicate of #224
