### ISSUE TITLE
[FEAT] : Develop Responsive About Page with Great UI

### ISSUE THREAD

**Issue by Vaibhavsg17** [singodiyashubham87/Draw-it-out#241]
**Is your feature request related to a problem? Please describe.**
Currently, our application lacks an About page, which is essential for providing users with information about the purpose, vision, and team behind "Draw-it-out." This can make it difficult for users to understand the mission of the tool and the people involved in its creation, leading to a lack of connection and trust.

**Describe the solution you'd like**
I propose developing a comprehensive and responsive About page that includes the following sections:

Introduction: Brief overview of "Draw-it-out" and its purpose.
Features: Highlights of the main features and benefits.
Team: Profiles of the team members, including photos and short bios.
Vision and Mission: Explanation of the project’s goals and values.
Contact Information: Ways for users to get in touch with us.
The page should be designed with a responsive layout to ensure it looks great on all devices, from desktops to smartphones, using TailwindCSS for styling.

**Describe alternatives you've considered**
We considered embedding the About information within the main page or as a pop-up modal, but these approaches may clutter the interface and detract from the main functionality of the tool. A dedicated About page allows for a cleaner, more focused presentation of this information.

**Comment by Vaibhavsg17** [comment]
@singodiyashubham87 please assign me this issue under SSoC'24

**Comment by singodiyashubham87** [comment]
@Vaibhavsg17 Sorry but as of now we don't need an about page.
