### ISSUE TITLE
[FEAT]: Adding undo feature

### ISSUE THREAD

**Issue by Archiesachin** [singodiyashubham87/Draw-it-out#242]
**Is your feature request related to a problem? Please describe.**
The whiteboard app has an clear the entire board feature. but to just undo the recent doodle there is no feature. 

**Describe the solution you'd like**
Adding a button on the top along with the shapes and pen option with the option of undo which will undo only the recent doodle on the whiteboard. 

**Additional context**
Assign  me this issue under GSSOC'24. Also add  the relevant labels.

**Comment by samiksha001** [comment]
Please assign this issue to me,i can help add a undo and redo option for the users which makes it easier for them

**Comment by singodiyashubham87** [comment]
@Archiesachin Duplicate of #32
