### ISSUE TITLE
Guidelines visibility on  dark mode

### ISSUE THREAD

**Issue by GOURAVSINGH19** [singodiyashubham87/Draw-it-out#244]
**Describe the bug**
Guidelines visibility on dark mode not clear 

**To Reproduce**
1. Click on 'dark mode '
2. click on 'guideline'

**Screenshots**
![Screenshot 2024-06-01 002653](https://github.com/singodiyashubham87/Draw-it-out/assets/120244528/7c7c230c-58e7-4469-bd4d-c79eea25310b)

**Comment by singodiyashubham87** [comment]
@GOURAVSINGH19 They are visible, the issue has been already fixed. Kindly explore other issues :)
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/93720428/aa28a34e-1fca-46b9-afe9-d2e8b404c825)
