### ISSUE TITLE
[FEAT]undo option not available

### ISSUE THREAD

**Issue by bishnudev35** [singodiyashubham87/Draw-it-out#247]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bishnudev35** [comment]
i want  to work on the issue

**Comment by Vanicoding27** [comment]
Please assign this task to me.

**Comment by singodiyashubham87** [comment]
@bishnudev35 Duplicate of #32
