### ISSUE TITLE
[DOCS] Addition of no of forks star issue closed open pr to readme.md

### ISSUE THREAD

**Issue by Anjaliavv51** [singodiyashubham87/Draw-it-out#249]
**Describe the changes that you want to make in the documentation**
A clear and concise description of the changes to be made in documentation
Addition of no of forks star issue closed open pr to readme.md and also Readmemd looks dull i would like to add gif emoji's.

**Significance of the changes made**
describe the effect of these changes

Gives attractiveness to Readme.md and also aslo looks cool.

**Comment by Anjaliavv51** [comment]
@singodi

**Comment by Anjaliavv51** [comment]
@singodiyashubham87

**Comment by Anjaliavv51** [comment]
@singodiyashubham87 
@soumya-maheshwari 

please review the PR

**Comment by singodiyashubham87** [comment]
@Anjaliavv51 How you going to implement this as these numbers changes everyday, how will they be updated?

**Comment by Anjaliavv51** [comment]
@singodiyashubham87 the links will be updated automatically

**Comment by singodiyashubham87** [comment]
@Anjaliavv51 Assigned, Best of Luck :)
