### ISSUE TITLE
[BUG] : Fix Alignment Issue of Chatbot and Gmail Icon in Footer

### ISSUE THREAD

**Issue by DebapriyaJha** [singodiyashubham87/Draw-it-out#253]
**Describe the bug**
The chatbot feature in the footer overlaps with the Gmail icon, causing the Gmail icon to go behind the chatbot and become not visible properly.

**To Reproduce**
1. Go to the website-  'https://draw-it-out.vercel.app/'
2. Scroll down to the footer section.
3. Observe the position of the chatbot and the Gmail icon.
4. Notice that the Gmail icon is hidden behind the chatbot.

**Expected behavior**
The Gmail icon should be clearly visible and not overlapped by the chatbot. The chatbot should be positioned in a way that does not interfere with the visibility of the Gmail icon.

**Screenshots**
![alignment](https://github.com/singodiyashubham87/Draw-it-out/assets/111692420/abf96c44-3cfd-4ee3-8c4b-36b876c23de2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

I would like to work on this issue. So, please assign me this issue under GSSOC'24. Also, add the gssoc24 and appropriate level labels to the issue.

**Comment by singodiyashubham87** [comment]
@DebapriyaJha Assigned you the issue, Best of Luck :)

**Comment by DebapriyaJha** [comment]
Thank you @singodiyashubham87 for assigning this issue to me.
I was going to start working on the PR but I think due to some error after merging some other PR the social media icons are not being displayed now in the footer.
![ali](https://github.com/singodiyashubham87/Draw-it-out/assets/111692420/b7121db4-09c6-4453-bf5c-c05e94851dd5)

So I was assigned to Fix Alignment Issue of Chatbot and Gmail Icon in Footer. I think before I can work on this issue I would like to create one more issue regarding the social media icons not being visible and it would be great if you could also assign that issue to me and share the link to your social media handles so that I can work on both my PR accurately.

**Comment by DebapriyaJha** [comment]
#339 I have added this new issue. Please assign this to me so that I can work smoothly on both my issue and solve both the issue accurately

**Comment by singodiyashubham87** [comment]
@DebapriyaJha The icons are still there, pull the main branch.
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/93720428/7a9bb520-9c71-4e22-89c7-56753b631ce6)

**Comment by DebapriyaJha** [comment]
Oh Okay. Sorry for the issue raised. It was due to some misunderstanding
