### ISSUE TITLE
[FEAT] Add Different Color Options for Drawing Pen

### ISSUE THREAD

**Issue by AsmitaMishra24** [singodiyashubham87/Draw-it-out#254]
**Is your feature request related to a problem? Please describe.**
- The current limitation to a single color for the pen restricts user creativity.
- Users are unable to highlight or differentiate between various elements in their drawings.

**Describe the solution you'd like**
- Offer a set of predefined colors (e.g., red, blue, green, yellow, black, white, etc).
- Simpler to implement, still provides more flexibility than the single-color option.
- Include a variety of colors for selection and easy switching during drawing.
- Make the color selection tool easily accessible (e.g., toolbar or dropdown menu).

**Describe alternatives you've considered**
Color Picker Tool:
- Implement a color picker tool for selecting any color from a spectrum.
- Provides maximum flexibility, though more complex to implement.

Themes:
- Offer themed color sets that change the drawing pen color along with other interface elements.
- Middle-ground solution, offering a range of colors without the complexity of a full color picker tool.

**Additional context**
- screenshot of previous work:-
![Screenshot 2024-05-31 193819](https://github.com/singodiyashubham87/Draw-it-out/assets/146121869/7f694689-316e-47be-b4d5-2e5e54f5785d)

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by Tanishka023** [comment]
Hey @singodiyashubham87 Please assign this issue to me, I can fix this.

**Comment by singodiyashubham87** [comment]
@AsmitaMishra24 There is an option of color picker & we can pick any color from there, what is the issue, can you clarify?

**Comment by AsmitaMishra24** [comment]
The issue has already been addressed. Apologies for bringing it up again.
