### ISSUE TITLE
[BUG] The guidelines in dark mode are not readable 

### ISSUE THREAD

**Issue by payalgupta25** [singodiyashubham87/Draw-it-out#257]
**Describe the bug**
When in dark mode , on clicking the guidelines icon the card which is being popped up isn't readable due to contrasting colors.

**To Reproduce**
1. Go to 'Guidelines icon'
2. Click on icon
3. A card will be popped up
4. See the color of font which is not readable 

**Expected behavior**
The font color should be darker so that its visible on light background

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/139633883/89d4b6a8-d482-4060-9080-4236c1a4de6d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : chrome

**Comment by hunxjunedo** [comment]
Hey @singodiyashubham87, kindly assign this issue to me, I'd like to contribute.

**Comment by Monalisha-Roy** [comment]
Please assign this issue to me. I can fix this issue smoothly.

**Comment by singodiyashubham87** [comment]
@payalgupta25 Update your forked repo, the guidelines are visible.
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/93720428/bac0efb4-79eb-410c-b985-022445aba304)
