### ISSUE TITLE
[FEAT] : Preloader

### ISSUE THREAD

**Issue by Jagpreet153** [singodiyashubham87/Draw-it-out#265]
**Is your feature request related to a problem? Please describe.**
Yes , adding a preloader would make the UI  more attractive

**Describe the solution you'd like**
I would be adding a animation in JSON format which would render until the page is being loaded

**Describe alternatives you've considered**
The page would be completely responsive and matching with the theme of site

**Additional context**
Kindly assign this issue to me under SSoC'24

**Comment by singodiyashubham87** [comment]
@Jagpreet153 Assigned you the issue, Best of Luck :)
