### ISSUE TITLE
# Bug Report: Persistent Drawing After Exiting Canvas

### ISSUE THREAD

**Issue by Atanu789** [singodiyashubham87/Draw-it-out#268]
**Describe the bug**
When drawing on the canvas, if the cursor exits the canvas area and then re-enters, the drawing continues even if the mouse is not clicked. Deleting the drawing does not resolve the issue; the drawing persists when the cursor is moved over the canvas.

**To Reproduce**
1. Go to the Draw-It-Out website.
2. Begin drawing on the canvas.
3. Move the cursor out of the canvas area while holding down the mouse button.
4. Re-enter the canvas area without clicking the mouse.
5. Observe that drawing continues even though the mouse button is not clicked.

**Expected behavior**
Drawing should only occur when the mouse button is actively pressed. Upon re-entering the canvas area, drawing should not continue unless the mouse button is clicked again.

**Additional context**
This issue may interfere with precise drawing and needs to be addressed for a smoother user experience.

**Comment by Atanu789** [comment]
Hey @singodiyashubham87
can you please assign me the issue.

**Comment by singodiyashubham87** [comment]
@Atanu789 Assigned you the issue, Best of Luck :)
