### ISSUE TITLE
[FEAT]: Adding Copyright Section

### ISSUE THREAD

**Issue by MuraliDharan7** [singodiyashubham87/Draw-it-out#271]
**Is your feature request related to a problem? Please describe.**
This feature request will provide all rights access to PA

**Describe the solution you'd like**
By adding copyright section PA ensure that the rights reserved for the project.

**Additional context**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/130668745/7db56108-c010-4177-a57b-488b3ed6b24f)

Please assign this to me under GSSoC'24.

**Comment by singodiyashubham87** [comment]
It's the wrong project, Be aware while creating issues.
