### ISSUE TITLE
[FEAT]: Adding Scroll to Top button

### ISSUE THREAD

**Issue by MuraliDharan7** [singodiyashubham87/Draw-it-out#272]
**Is your feature request related to a problem? Please describe.**
When there is a product with more elements and contexts, they should have the scroll to top button to faster the process when someone needs to come at the top.

**Describe the solution you'd like**
The scroll to top button should be added which takes us to the top of the page.

**Additional context**
Please assign this to me under GSSoC'24.

**Comment by mahiv04** [comment]
can you assign me this issue under ssoc'24

**Comment by KavyaBS123** [comment]
Hey @singodiyashubham87 I am GSSOC contributor can you please assign this issue to me I would like to work on it!

**Comment by singodiyashubham87** [comment]
@MuraliDharan7
