### ISSUE TITLE
[BUG] The End Chat button is on the same line and looks weird

### ISSUE THREAD

**Issue by Wahid7852** [singodiyashubham87/Draw-it-out#273]
**Describe the bug**

**To Reproduce**
The end chat button looks like normal text
"!End Chat"

**Expected behavior**
Should be on a new line and with a different color, probably

**Comment by Wahid7852** [comment]
maybe assign me for gssoc stuff, i will do a PR by the time

**Comment by singodiyashubham87** [comment]
@Wahid7852 Assigned you the issue, Best of Luck :)

**Comment by Wahid7852** [comment]
kindly check #274
