### ISSUE TITLE
[BUG] Not compatible with mobile screen.

### ISSUE THREAD

**Issue by Madhavdua** [singodiyashubham87/Draw-it-out#275]
**Describe the bug**
It does not appear properly on mobile device.

**To Reproduce**
1. Go to Inspect 
2. Select any mobile screen
OR
View directly on mobile device

**Expected behavior**
It should appear properly on mobile.

**Screenshots**
![Screenshot 2024-06-02 205412](https://github.com/singodiyashubham87/Draw-it-out/assets/94641232/c0706cf1-2ce1-4b61-8cba-37692a6592c3)
![Screenshot 2024-06-02 205528](https://github.com/singodiyashubham87/Draw-it-out/assets/94641232/7668c562-7497-4730-be3e-e15551688954)

**Comment by singodiyashubham87** [comment]
@Madhavdua This issue is already open & someone is working to fix it, Wait until he make the PR.

**Comment by Madhavdua** [comment]
Thank you for updating me.
I'll look for any further improvement suggestions.

**Comment by singodiyashubham87** [comment]
Issue fixed.
