### ISSUE TITLE
Adding an "Help Us Improve!" button

### ISSUE THREAD

**Issue by AkshitGarg24** [singodiyashubham87/Draw-it-out#277]
The website currently lacks a 'Help Us Improve!' button, which can replace the 'Contact Us' section. A dedicated web page should be created for this purpose. Users can utilize this feature when they encounter technical issues or glitches, or if they want to provide suggestions or request new features. This approach will help us understand the issues users are facing and what they desire from the website.

Although users can raise issues on GitHub, but this website is accessible to people of all ages and technical backgrounds. Many users may not know how to use GitHub to request features or report issues, making it an unfriendly option. Therefore, a user-friendly, dedicated web page is essential for capturing user feedback effectively.

As a GSSoC'24 contributor, I want to work on this issue.

Thank You!

**Comment by singodiyashubham87** [comment]
@AkshitGarg24 It's a Single Page application & we don't want any other page.

**Comment by AkshitGarg24** [comment]
@singodiyashubham87 Instead of creating a dedicated web page, I can implement a dialog box that displays the Contact Us form directly on the main page. When the Contact Us button is clicked, a box containing the Contact Us form will appear on the main page itself.
