### ISSUE TITLE
[FEAT] Missing Option for Drawing Straight Lines in Menu

### ISSUE THREAD

**Issue by Atanu789** [singodiyashubham87/Draw-it-out#287]
## Describe the bug
A user has reported that the Draw-it-Out website does not include an option for drawing straight lines in the menu.

## To Reproduce
1. Go to the Draw-it-Out website.
2. Click on the menu button.
3. Navigate through the options.
4. Observe that there is no option for drawing straight lines.

## Expected behavior
Users expect to find an option in the menu that allows them to draw straight lines.

## Additional context
The absence of the straight line drawing option is limiting users' ability to create precise diagrams and shapes. This issue may impact the usability and functionality of the Draw-it-Out application.

**Comment by Atanu789** [comment]
hey @singodiyashubham87
Can you please assign me this issue under ssoc24

**Comment by mondalsurojit** [comment]
@singodiyashubham87 If somehow the author is not interested with this feature later, or finds any better feature to work on...In that case, I am willing to work on this feature under SSOC'24.

**Comment by singodiyashubham87** [comment]
@Atanu789 Assigned you the issue, Best of Luck :)
