### ISSUE TITLE
[DOCS]: Document Basic Drawing Tools

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/Draw-it-out#30]
**Describe the changes that you want to make in the documentation**
Create a new section in the documentation that explains how to use the basic drawing tools available in Draw-it-out, including the pencil, eraser, and color picker.

**Significance of the changes made**
This will provide new users with clear instructions on how to utilize the essential drawing features of Draw-it-out, improving their overall experience with the application.

**Comment by RicardoHaranoP** [comment]
hello, i made a PR for this issue. Can you check it out?

**Comment by singodiyashubham87** [comment]
@RicardoHaranoP Kindly read the contributor's guidelines first, it's clearly mentioned that you must first be assigned an issue before working on the issue.
Secondly, you made an unnecessary PR, it's not solving the issue.

**Comment by iamkanhaiyakumar** [comment]
I'm excited to contribute to the Draw-it-out project. Could you please assign me.

**Comment by aaryaparadkar** [comment]
Hey @singodiyashubham87 ! Would very much like to contribute to 'Draw-it-out'. Would you be willing to assign this to me? Cheers!

**Comment by Adi-gitX** [comment]
Description: Add a new section to Draw-it-out's documentation with clear instructions on how to use the basic drawing tools - pencil, eraser, and color picker - effectively.

Significance: By providing new users with clear instructions on using essential drawing tools, it will enhance their overall experience with the application and enable them to create artwork more efficiently.

i would like to work on this, please assign me this issue

**Comment by singodiyashubham87** [comment]
@aaryaparadkar Best of Luck!
