### ISSUE TITLE
[FEAT] Add Review Functionality - User Rating and Comment Feature

### ISSUE THREAD

**Issue by Atanu789** [singodiyashubham87/Draw-it-out#300]
**Description:**
Add a feature enabling users to rate and comment on different aspects of the website, enhancing engagement and feedback. 

**Requirements:** 
1. Create a review button.
2. Enable rating on a scale and comment submission.
3. Validate input before submission.
4. Allow viewing existing reviews with moderation options.
5. Ensure responsiveness and accessibility.

**Comment by Atanu789** [comment]
hey @singodiyashubham87
kindly assign me this issue under #ssoc24

**Comment by singodiyashubham87** [comment]
@Atanu789 No need as of now.
