### ISSUE TITLE
A better favicon for the website

### ISSUE THREAD

**Issue by spacedust26** [singodiyashubham87/Draw-it-out#301]
**Is your feature request related to a problem? Please describe.**
The favicon is really small and not so clearly visible.

**Describe the solution you'd like**
A bigger and more visible favicon that is suitable for the website would enhance the overall look.
I'd like to make a colorful and apt favicon pertaining to the theme of the website.

@singodiyashubham87 could you please assign this issue to me under gssoc'24?

**Comment by singodiyashubham87** [comment]
@spacedust26 @KavyaBS123 Both of you can show me your prototypes & if any feels good to me for the application, I'll choose that & assign the issue to that person.

**Comment by singodiyashubham87** [comment]
@spacedust26 The Last one looks good, Assigning you the issue :)
