### ISSUE TITLE
[BUG] Misalignment of curser and pen.

### ISSUE THREAD

**Issue by hrishabhpatel09** [singodiyashubham87/Draw-it-out#303]
**Describe the bug**
A curser is having a lag from the pen that is drawing items in a clipboard.

![Screenshot (57)](https://github.com/singodiyashubham87/Draw-it-out/assets/153719095/f4fb0a3c-70fb-4e7a-b742-eb054d21d1f2)

i was unable to show my curser in this screenshot as it is getting hidden but you can try yourself.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by singodiyashubham87** [comment]
@hrishabhpatel09 Are you an GSSOC or SSOC contributor?

**Comment by shreyarao9** [comment]
Can you assign this issue to me?

**Comment by singodiyashubham87** [comment]
@shreyarao9 GSSOC or SSOC?

**Comment by shreyarao9** [comment]
@singodiyashubham87 SSOC
