### ISSUE TITLE
[BUG] Issue with the background colour settings 

### ISSUE THREAD

**Issue by Jasleen1210** [singodiyashubham87/Draw-it-out#305]
The site features a panel for canvas colours at the left side, however the custom color picker in that panel does not reflect the colour onto the canvas. This does not allow a user to easily choose colours for the backdrop of their project.

The correct behavior should be that the colour chosen by the user should be reflected in the existing canvas area as well as new canvas area that user might decide to add later. Also there should be some sort of label provided above that panel that allows the user to figure out that it is used for changing the background colour of the project.

**Comment by Jasleen1210** [comment]
Please assign me this issue.

**Comment by singodiyashubham87** [comment]
@Jasleen1210 Follow the issue template while creating issues.
