### ISSUE TITLE
[DOCS]: Write Installation Guide

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/Draw-it-out#31]
**Describe the changes that you want to make in the documentation**
Draft a comprehensive guide that outlines the step-by-step process for installing and setting up Draw-it-out locally on different operating systems (Windows, macOS, Linux).

**Significance of the changes made**
By providing clear installation instructions, we can lower the barrier for new users to get started with Draw-it-out, encouraging wider adoption of the application.

**Comment by iamkanhaiyakumar** [comment]
I'm excited to contribute to the Draw-it-out project. Could you please assign me.

**Comment by aaryaparadkar** [comment]
Hey @singodiyashubham87 ! Would love to contribute to this. Would you be willing to assign this to me? Cheers!

**Comment by singodiyashubham87** [comment]
@iamkanhaiyakumar Proceed!

**Comment by iamkanhaiyakumar** [comment]
Thank You @singodiyashubham87

**Comment by Niharika-Behera** [comment]
Kindly assign this issue to me.I can fix it.@singodiyashubham87

**Comment by singodiyashubham87** [comment]
@iamkanhaiyakumar Are you working on the issue or should I assign it to the next contributor?

**Comment by iamkanhaiyakumar** [comment]
Yes sir, and sorry for being late, my mid-sem exam was going on, so I have done only half the work, I will submit it by tomorrow and thank you.
