### ISSUE TITLE
[FEAT]: Eraser tool or undo option

### ISSUE THREAD

**Issue by anwesha2002** [singodiyashubham87/Draw-it-out#319]
**Is your feature request related to a problem? Please describe.**
There is no undo option or eraser tool for a drawing. There is an option to erase everything not for a particular steps

**Describe the solution you'd like**
I want to provide options for updo a step of erase a particular portion

**Describe alternatives you've considered**

**Additional context**
I am a gssoc'24 contributor. please assign this to me

**Comment by singodiyashubham87** [comment]
Duplicate of #32  #36
