### ISSUE TITLE
[FEAT] Cursor style

### ISSUE THREAD

**Issue by Jasleen1210** [singodiyashubham87/Draw-it-out#322]
**Is your feature request related to a problem? Please describe.**
The current cursor looks plain, we can enhance it by replacing it with brush pen icon. 

**Describe the solution you'd like**
Adding cursor styles will improve the overall user experience.

**Describe alternatives you've considered**

**Additional context**
Please assign this issue to me under gssoc'24.

**Comment by singodiyashubham87** [comment]
Duplicate of #199
