### ISSUE TITLE
Eraser tool

### ISSUE THREAD

**Issue by aapJoysakoi** [singodiyashubham87/Draw-it-out#325]
**Is your feature request related to a problem? Please describe.**
A button to clear the full canvas but what if I want to erase just a part of it?

**Describe the solution you'd like**
Add an eraser tool which will provide the user with an option to partially erase a part of the artwork.

**Comment by aapJoysakoi** [comment]
please assign me this issue under SSOC.

**Comment by singodiyashubham87** [comment]
Duplicate of #36
