### ISSUE TITLE
Dashed and dotted feature not working

### ISSUE THREAD

**Issue by aapJoysakoi** [singodiyashubham87/Draw-it-out#326]
**Describe the bug**
The dashed and dotted functions aren't working

**Expected behavior**
Successful function of all the options i.e. dashed, dotted, solid, faded. (only solid and faded are functional currently.)

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/114143879/6a15f4f5-aac6-478a-8580-6add8c67f334)

**Comment by aapJoysakoi** [comment]
Please assign me this issue under SSOC

**Comment by singodiyashubham87** [comment]
@aapJoysakoi It's working. What's the issue?
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/93720428/819c75e4-bb66-479e-a1cd-725b247c40f0)

**Comment by aapJoysakoi** [comment]
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/114143879/5d9379be-0ade-4e67-8c30-96af66ab5af4)
my bad, only dashed line isn't working, dotted is fine. For shapes it is working though but line.
