### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by aapJoysakoi** [singodiyashubham87/Draw-it-out#327]
**Is your feature request related to a problem? Please describe.**
Unavailability of labels on the left color picker for background color and some other features as well.

**Describe the solution you'd like**
Add labels for different features for better accessibility. 

** screenshots **
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/114143879/e085c110-a318-453b-a5e3-25913cdbff0f)

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/114143879/944307af-b065-45b2-9d96-71926b45ca01)

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/114143879/452613bd-107f-4561-bbda-856181df331b)

**Comment by singodiyashubham87** [comment]
@aapJoysakoi What's this title of issue "Labels", At least be specific with issue names, follow standard guidelines.
