### ISSUE TITLE
Separating the Nav bar and Footer sections

### ISSUE THREAD

**Issue by Gultreen** [singodiyashubham87/Draw-it-out#330]
To separate the navbar and footer sections in your web application, we need to make changes to your HTML .

![Draw-it-out-](https://github.com/singodiyashubham87/Draw-it-out/assets/145576858/976ad48e-51b5-414a-b634-18149d0270ae)

Significance of the Changes Made
1. Semantic HTML Structure
2. Enhanced Readability and Maintenance

_**@singodiyashubham87**_ please assign me this issue under GSSoC'24.

**Comment by singodiyashubham87** [comment]
@Gultreen But there is no navbar in the app, it's just footer, what you want to do, elaborate please.

**Comment by Gultreen** [comment]
It's generally true that the footer section doesn't contain primary navigation links like "Home" (As we know that home comes on the nav bar )and "News." Instead, footers typically include secondary information such as contact details, copyright information, privacy policies, social media links, and sometimes additional navigation links for less critical sections of the website.
 
that's why I want to separate it.

**Comment by singodiyashubham87** [comment]
@Gultreen Yes, you are right & this issue is already being resolved via #226, If you want to add anything else then do tell me, once that issue is closed & your enhancement is worthy enough, I'll assign this issue to you :)

**Comment by Gultreen** [comment]
Social media icons in footer section is hidden by chatbot icon.

**Comment by singodiyashubham87** [comment]
@Gultreen For that also there is ongoing issue #234 , wait for both these issues to be closed.
