### ISSUE TITLE
Adding new feature of Login and SignUp page

### ISSUE THREAD

**Issue by Gultreen** [singodiyashubham87/Draw-it-out#331]
A login and signup page should be at starting of the website so that the there will be some kind of security in the website. 
Can you please assign me the issue under GSSOC'24 ?

**Comment by piyushmishraa** [comment]
So do we have  to create a login/signup page ?

**Comment by singodiyashubham87** [comment]
@Gultreen We really don't need this. Thanks for raising the issue :)
