### ISSUE TITLE
[FEAT] Disable text selection on website.

### ISSUE THREAD

**Issue by SahilThakur02** [singodiyashubham87/Draw-it-out#332]
**Is your feature request related to a problem? Please describe.**
Yes, in addition to protecting sensitive information, disabling text selection can improve the overall user experience by preventing accidental text selection while navigating the website, especially on touch devices.

<img width="326" alt="Screenshot 2024-06-07 203556" src="https://github.com/singodiyashubham87/Draw-it-out/assets/112742544/0dd205e9-9902-496c-ad1e-c1d82e40fd51">

**Comment by SahilThakur02** [comment]
I wish to start working on this issue , please /assign me this issue under GSSOC'24
@singodiyashubham87

**Comment by singodiyashubham87** [comment]
@SahilThakur02 What is the security issue related to text selection?

**Comment by SahilThakur02** [comment]
@singodiyashubham87 not very big of a security breach but your text can be copied that's all, 
- main idea behind disabling selection is to improve UI as disabling text selection looks more clean.

**Comment by singodiyashubham87** [comment]
@SahilThakur02 Assigned you the issue, Best of Luck :)
