### ISSUE TITLE
[Feature Request]:  Style added to Scrollbar

### ISSUE THREAD

**Issue by SrinivasDevolper** [singodiyashubham87/Draw-it-out#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a style to the scrollbar that looks good and gives a better user experience.

I expect to add level 2 on this task because it takes time and try-error to fix the style for the scrollbar.

**I am GSSOC24 Contributor
Please assign me, I would like to work on it**

### Use Case

Better user experience

### Benefits

Better user experience

### Add ScreenShots

![scrollbar](https://github.com/singodiyashubham87/Draw-it-out/assets/121508628/4f87547d-9430-4486-a7ce-df450b0a753e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@SrinivasDevolper Make the style of scrollbar matching to the application theme.

**Comment by SrinivasDevolper** [comment]
sure, which color would like to add

**Comment by singodiyashubham87** [comment]
@SrinivasDevolper Try the gray one, a combo of B&W, or else do Hit n Trial & share screenshots of multiple colors, I'll tell you which one to use.

**Comment by SrinivasDevolper** [comment]
![scrollbar 2](https://github.com/singodiyashubham87/Draw-it-out/assets/121508628/56137ece-6008-42f7-a980-c7c537db9b28)

![scrollbar3](https://github.com/singodiyashubham87/Draw-it-out/assets/121508628/664fdfb4-8c4d-408f-bee3-3ff847a95d62)

**Comment by singodiyashubham87** [comment]
@SrinivasDevolper It'll be better if you can give screenshot of how the scrollbars will look in the app.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@singodiyashubham87

**Comment by SrinivasDevolper** [comment]
![drawscroll3](https://github.com/singodiyashubham87/Draw-it-out/assets/121508628/94ee38d5-6108-42f9-b2f5-b3c954f3410d)

![drawscroll2](https://github.com/singodiyashubham87/Draw-it-out/assets/121508628/bf65ebe3-7552-4e35-a322-ff938906d997)

![drwascroll1](https://github.com/singodiyashubham87/Draw-it-out/assets/121508628/5ddfc8b1-e0cd-4b71-b285-80718b2bb5dd)

Which one would you like? if you are not satisfied can you suggest some styling colors?

**Comment by SrinivasDevolper** [comment]
ok, I will do with the first one, please assign me.

**Comment by soumya-maheshwari** [comment]
@SrinivasDevolper,  assigned you the issue, Best of Luck :)
