### ISSUE TITLE
[Feature Request]:  Developing each page for the requested tab in the bar

### ISSUE THREAD

**Issue by K-Svayam05** [singodiyashubham87/Draw-it-out#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/141111900/c918b295-e2cb-40a5-995b-9e023f5ef0b8)

On clicking all these tabs the Home page is directed. I want to add the feature of Contact, About and the others as well thus making these tabs function properly and also enhancing the features of the website.

Please assign me this issue
I am a GSSoC'24 Contributor, proficient in HTML, CSS, JavaScript and having good knowledge of React.js and Web Design as well.

### Use Case

On adding the pages for Contact and About, the reach of this website can be increased through social media. Also we could credit the Team behind building and developing this website; also News section can hold some art based facts or news depending on the necessity of it.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@K-Svayam05 Already being fixed in #234 & #226

**Comment by K-Svayam05** [comment]
> @K-Svayam05 Already being fixed in #234 & #226

Okay Sir. Do consider Me for any future issues! Would love to work on this project :)

**Comment by singodiyashubham87** [comment]
@K-Svayam05 The app still needs too much improvement so you can find bugs that you can fix or enhancements that you can make & create issues for the same after checking whether there is already any issue regarding that or not.
