### ISSUE TITLE
[Bug]: Non Visibility and No Effects of BuyMeACoffee Icon

### ISSUE THREAD

**Issue by shivamm-verma** [singodiyashubham87/Draw-it-out#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- The BuyMeACoffee icon was not visible in Dark mode.
- Also, It had no scale-up hover effects like the neighborhood icons

### Expected behavior

- The icon should be visible in both dark and light modes; 
- with similar scaling up hover effects;
- with smooth transitions

### Add ScreenShots

#Before
![before1_light](https://github.com/singodiyashubham87/Draw-it-out/assets/98605616/9bb4d03e-7669-42df-9def-23aa94fb40c2)
![before2_dark](https://github.com/singodiyashubham87/Draw-it-out/assets/98605616/8390f598-3341-41e1-9e3b-8d59a672ca0b)

#After
![after1_fixed_darkSS](https://github.com/singodiyashubham87/Draw-it-out/assets/98605616/1bb4d12e-58d8-43ac-aa23-e9711658665a)
![after2_fixed_lightSS](https://github.com/singodiyashubham87/Draw-it-out/assets/98605616/7b792963-5762-4fcb-ad39-5c48eb335188)

## Screen Recording
https://github.com/singodiyashubham87/Draw-it-out/assets/98605616/8dd615b8-3469-4a53-89ee-7f633d12c749

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by shivamm-verma** [comment]
Please @singodiyashubham87 ,
Assign me this Issue so that I can start working on it.

**Comment by shivamm-verma** [comment]
## White Bg to BuyMeACoffee icon is more better on the Dark Mode (than gray)

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/98605616/f39d7b96-deaa-47d1-a1bc-6a78b12d85e6)

**Comment by singodiyashubham87** [comment]
@shivamm-verma If you have searched the issues then haven't you saw this one https://github.com/singodiyashubham87/Draw-it-out/issues/236 ?
Duplicate issue, Closing.
