### ISSUE TITLE
[Feature Request]:  Add social media links and icons to the footer

### ISSUE THREAD

**Issue by DebapriyaJha** [singodiyashubham87/Draw-it-out#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to request the addition of social media links and icons to the footer section of the website to the official social media accounts, such as Twitter, Facebook, LinkedIn, and Instagram.

### Use Case

Having social media links and icons in the footer would make it easier for visitors to find and follow the official social media accounts. It would also provide a consistent way for users to stay up-to-date with the latest news, updates, and community interactions across various social media platforms.

### Benefits

Adding social media links and icons to the footer would bring the following benefits:
1) Increased visibility and accessibility of the social media accounts.
2) Enhanced user engagement and community-building opportunities.
3) Improved user experience by providing convenient access to the social media presence.

### Add ScreenShots

Before:
![ali](https://github.com/singodiyashubham87/Draw-it-out/assets/111692420/22818304-90d0-4a73-a0a8-59126cc4f518)
after:
![after](https://github.com/singodiyashubham87/Draw-it-out/assets/111692420/97efe5d0-9650-494f-a1eb-613600541008)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@DebapriyaJha Footer is already being enhanced & fixed by the issues #234 & #226
