### ISSUE TITLE
[FEAT]: Add Export to SVG/PDF

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/Draw-it-out#34]
**Is your feature request related to a problem? Please describe.**
Users often need to export their drawings in scalable vector graphics (SVG) or portable document format (PDF) for printing or further editing, but currently, Draw-it-out only supports image exports.

**Describe the solution you'd like**
Extend the export functionality to include options for exporting drawings as SVG or PDF files, preserving scalability and editability.

**Describe alternatives you've considered**
An alternative could be allowing users to export to other common formats like JPEG or PNG, but SVG and PDF offer better support for vector graphics.

**Additional context**
This feature would enhance Draw-it-out's usefulness for professional users who need high-quality output for printing or integration into other design software.

**Comment by akilesh1706** [comment]
@singodiyashubham87 I'm ready to work on this issue as a part of GSSoC'24. I request you to assign it to me.

**Comment by Vidip-Ghosh** [comment]
I would like to work on it. Please assign this to me.

**Comment by porwalshreyaa** [comment]
Can you assign this to me?
I wanna contribute for GSSoC 24.

**Comment by singodiyashubham87** [comment]
@Vidip-Ghosh Assigned!
