### ISSUE TITLE
Automatic copyright[Documentation Update]: 

### ISSUE THREAD

**Issue by dishathakurata** [singodiyashubham87/Draw-it-out#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The current copyright is manual and the year needs to change every year manually.

### Suggested Change

I can make the copyright automatic which does not need to change every year manually, but will be changed automatically.

### Rationale

This update is necessary to reduce human labor every year, and can be handled automatically by js.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@dishathakurata You can only complete the issue under any one program, which one do you want SSOC or GSSOC?

**Comment by dishathakurata** [comment]
GSSoC

**Comment by singodiyashubham87** [comment]
@dishathakurata Assigned you the issue, Best of Luck :)
