### ISSUE TITLE
[Feature Request]: Designing Contact US Page for website

### ISSUE THREAD

**Issue by Prithwi32** [singodiyashubham87/Draw-it-out#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

contact us page is very much important in every website, through which users connect with owner for further quires and help

### Use Case

If user want to get help from owner he can connect them through contact form

### Benefits

Community bounding increases

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@singodiyashubham87 I would like to work on this issue under gssoc'24

**Comment by singodiyashubham87** [comment]
@Prithwi32 Do search for another open issue before creating any new issue, This is already being resolved under issue #226 .
