### ISSUE TITLE
[Feature Request]: Design our team Page

### ISSUE THREAD

**Issue by Prithwi32** [singodiyashubham87/Draw-it-out#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

in our team page, we can add all contributed profile, like linking to their github profiles

### Use Case

By displaying contributers in our team page, we increases chances like, user also involves in contributing and it will showcase work of collaborators and contributers

### Benefits

It it will be like honour to the contributers

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@singodiyashubham87  I would like to work on this issue under gssoc'24
please could u assign this to me

**Comment by singodiyashubham87** [comment]
@Prithwi32 Do search for another open issue before creating any new issue, This is already being resolved under issue #226 .
