### ISSUE TITLE
[Feature Request]: News Page design

### ISSUE THREAD

**Issue by Prithwi32** [singodiyashubham87/Draw-it-out#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

By introducing news page, it will help user to be up to date with the modern design tools and technology

### Use Case

user gets updates on new design tools and techs

### Benefits

increases usage of our website more by users

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@singodiyashubham87  I would like to work on this issue under gssoc'24
please could u assign this to me

**Comment by singodiyashubham87** [comment]
@Prithwi32 Do search for another open issue before creating any new issue, This is already being resolved under issue #226 .
