### ISSUE TITLE
[Feature Request]: Navbar with links to other pages like About Us and Contact Us to better User Experience

### ISSUE THREAD

**Issue by r7projects-shayan** [singodiyashubham87/Draw-it-out#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There is currently no navbar that has links to other pages, people will have to scroll down to the footer to navigate, which poses a bad user experience for the website.

The top portion is empty, a navbar can easily be accommodated there

### Use Case

There should be a navbar for better user experience across the website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by r7projects-shayan** [comment]
@singodiyashubham87 Kindly assign me this major issue

**Comment by singodiyashubham87** [comment]
@r7projects-shayan This app was not built in a way that it should have a navbar.
