### ISSUE TITLE
[Feature Request]:  Adding Docker to the project

### ISSUE THREAD

**Issue by Ratangulati** [singodiyashubham87/Draw-it-out#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Docker is a must for open-source projects nowadays as it has its benefits.

### Use Case

Use Case
Dockerfile has many benefits but consistency and isolation stand out the most.

Docker allows you to package your entire application, including its dependencies, into a single container. That makes sure your application will run across different environments.
another benefit is that it runs in its environment without interfering with other applications or the host system.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@Ratangulati Select only one from GSSOC & SSOC as you can't get points in both projects for one issue.

**Comment by Ratangulati** [comment]
Sorry about that.

**Comment by singodiyashubham87** [comment]
@Ratangulati It's Okay, I've assigned you the issue, Best of Luck :)
