### ISSUE TITLE
[Feature Request]: Adding the About page 

### ISSUE THREAD

**Issue by Maheshwari-Love** [singodiyashubham87/Draw-it-out#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding the about page for knowing what is this project is and how this works who made it...

### Use Case

An "About" page is essential for building trust and credibility by introducing the team and showcasing expertise. It communicates the project's purpose, values, and background, enhancing user engagement and connection. It also aids in SEO and consistent branding while providing transparency and guiding users to further explore the project.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@singodiyashubham87 can you please assign this task to me?

**Comment by singodiyashubham87** [comment]
@Maheshwari-Love The app was supposed to have only a single page, So we can't have any about page.

**Comment by Maheshwari-Love** [comment]
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/142833275/8b8c89f6-1475-46e4-959d-fa96f8e86fe4)
then what about this?

**Comment by singodiyashubham87** [comment]
@Maheshwari-Love They are being resolved in issue #226
