### ISSUE TITLE
[FEAT] Add Eraser

### ISSUE THREAD

**Issue by kailashchoudhary11** [singodiyashubham87/Draw-it-out#36]
As a user, I Should be able to erase the drawing that I made so that I can remove the unwanted parts of the drawing.

**Comment by ayan-joshi** [comment]
I would like to work on this can u assign this issue to me

**Comment by singodiyashubham87** [comment]
@ayan-joshi Assigned!
Kindly read the contributing guidelines before contributing.
Best of Luck! :)

**Comment by PoojaGadagi08** [comment]
Hello @singodiyashubham87  sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by porwalshreyaa** [comment]
@singodiyashubham87  I see that this issue is assigned to him but if he couldn't do or exceed time then you can assign to me, I have the solution in my mind already.

**Comment by singodiyashubham87** [comment]
@ayan-joshi Are you still working on the issue or should I assign it to the next candidate?

**Comment by ayan-joshi** [comment]
> @ayan-joshi Are you still working on the issue or should I assign it to the next candidate?

I will create pr in 1 or 2 days , my exams are going on , give me some time @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@ayan-joshi Okay, Best of Luck!

**Comment by singodiyashubham87** [comment]
@PoojaGadagi08  Wanna work on the issue?

**Comment by singodiyashubham87** [comment]
@Sanj-bot If the people asked before you rejects the issue then I'll assign it to you, Have patience.

**Comment by singodiyashubham87** [comment]
@Sanj-bot Want to work on the issue?

**Comment by revanth1718** [comment]
@singodiyashubham87 if this issue is still open, please assign this to me under GSSOC'24.

**Comment by singodiyashubham87** [comment]
@revanth1718 This issue is now being resolved in #404
