### ISSUE TITLE
[Bug]: Mail icon is not visible 

### ISSUE THREAD

**Issue by ronisarkarexe** [singodiyashubham87/Draw-it-out#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

mail icon is not visible 

### Expected behavior

When I am at the bottom, it should be displayed.

### Add ScreenShots

![email_icon](https://github.com/singodiyashubham87/Draw-it-out/assets/76697055/e3be801f-32cd-4b0b-9a6f-1d5665c753b1)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
You're assigned @ronisarkarexe!

**Comment by 0xabdulkhalid** [comment]
Hi there @ronisarkarexe 👋🏻 

There's already an issue which is relatable to yours #253 

Since this issue is duplicate, I'm closing this for now.

Thank you for your contribution!
