### ISSUE TITLE
[Bug]: Brush Dropdown Menu

### ISSUE THREAD

**Issue by Yashaswale** [singodiyashubham87/Draw-it-out#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when we select the brush icon and start to draw without selecting any it does not dissapper 

### Expected behavior

when we click on the brush icon and then click anywhere else it should disappear

### Add ScreenShots

https://github.com/singodiyashubham87/Draw-it-out/assets/117583791/d242134f-b88e-4588-9c01-e977c6e18f62

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
You're assigned @Yashaswale, create a PR once you fixed the Bug!
