### ISSUE TITLE
[Feature Request]: Add sinin/signup page

### ISSUE THREAD

**Issue by MuraliDharan7** [singodiyashubham87/Draw-it-out#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add sign in/ sign up page 

### Use Case

This will ensure the admin who is using the app. also help users to know the latest updates

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hi there @MuraliDharan7 👋🏻 

We don't need Sign-in/Sign-up Page for now, because Draw-it-out's main theme is to provide a instant drawing board without any authentication.

@singodiyashubham87 what's your thoughts on this issue?

**Comment by singodiyashubham87** [comment]
@0xabdulkhalid Yes, we don't want this feature as of now.
