### ISSUE TITLE
Add dynamic year code in footer as well give margin 

### ISSUE THREAD

**Issue by arpit4521** [singodiyashubham87/Draw-it-out#366]
![Screenshot 2024-06-11 213329](https://github.com/singodiyashubham87/Draw-it-out/assets/127679958/4e801444-939e-4daf-a0f8-d13b038a585b)

@singodiyashubham87 please assign it to me under gssoc and apt level label

**Comment by soumya-maheshwari** [comment]
Hi @arpit4521 
we are already having dynamic year code in footer

**Comment by Shahbaz898414** [comment]
can you assign me this issue?

**Comment by arpit4521** [comment]
@singodiyashubham87 i need to add margin in the footer please assign under gssoc level1

**Comment by singodiyashubham87** [comment]
@arpit4521 The year is already dynamic.
