### ISSUE TITLE
[Documentation Update]: Add PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by codercake** [singodiyashubham87/Draw-it-out#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

It’s essential to provide a detailed explanation of how this feature works and its implementation.

### Suggested Change

This should include:
1. A step-by-step guide on how the feature operates.
2. Code snippets illustrating the implementation.
3. Security considerations and best practices.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
You're assigned @codercake!

**Comment by 0xabdulkhalid** [comment]
we don't need a PR Template for now, because we already have one. Since the change you Proposed on PR is not good enough, the existing one seems to be good.

Thank you for your Contribution!
