### ISSUE TITLE
Respoonsive for the mobile screen to enhance the user experience on all device

### ISSUE THREAD

**Issue by Utsavladia** [singodiyashubham87/Draw-it-out#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Responsive for the mobile screen 
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/124615886/a1a542d2-56ce-4363-beb0-32c1a2a434b6)

### Use Case

It should be responsive  for the all users.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@Utsavladia It's been resolved.

**Comment by Shahbaz898414** [comment]
can you assign me this issue?
