### ISSUE TITLE
Hover on selecting shape to enhance user experinece

### ISSUE THREAD

**Issue by Utsavladia** [singodiyashubham87/Draw-it-out#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There should be a hover on shape selection. 

### Use Case

Enhance the user experinece.
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/124615886/202d605a-b9b0-4b01-9534-a917d4afa49c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@Utsavladia Select only one, either GSSOC or SSOC.

**Comment by Utsavladia** [comment]
@singodiyashubham87  sure I seleted GSSoC

**Comment by singodiyashubham87** [comment]
@Utsavladia Assigned! Best of luck :)
