### ISSUE TITLE
[Bug]: About and Contact Us links in the footer are not working 

### ISSUE THREAD

**Issue by Satuti99** [singodiyashubham87/Draw-it-out#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicking on the "About Us" and "Contact Us" links on the website, both links redirect users to the same page. This issue causes confusion and prevents users from accessing the specific information they are looking for, whether it is about the organization or how to get in touch.

### Expected behavior

The "About Us" link should direct users to a dedicated page that provides detailed information about the organization, its mission, vision, history, and team. The "Contact Us" link should direct users to a separate page that includes contact details, a contact form, and possibly additional information .

### Add ScreenShots

https://github.com/singodiyashubham87/Draw-it-out/assets/115169702/4f3fb4b2-0aa5-452a-8b6b-5b8dd45a2a95

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@Satuti99 This issue is being resolve in #226

**Comment by Satuti99** [comment]
Ok Sir @singodiyashubham87. Thank you for bringing this to my attention. If it's not resolved, please  consider assigning it to me in the future.
