### ISSUE TITLE
[FEAT] Option to Hide the buttons and bg choices

### ISSUE THREAD

**Issue by kailashchoudhary11** [singodiyashubham87/Draw-it-out#38]
There should be an option to hide the background color choices and also the other buttons so that the user can focus more on drawing.

**Comment by shivamb11** [comment]
Hello, I am ready to work on this feature. Can you assign it to me ?

**Comment by GayathriThejus** [comment]
I agree to this, I also feel the UI palette doesn't seem visually appealing & the picture doesn't get removed on adjusting the pen size, instead to have an eraser option. Can the work be assigned to me?

**Comment by singodiyashubham87** [comment]
@shivamb11 Best of Luck!

**Comment by shivamb11** [comment]
Okay thanks, working on it.
