### ISSUE TITLE
Add Icons 

### ISSUE THREAD

**Issue by sailaja-adapa** [singodiyashubham87/Draw-it-out#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add icons to items 

Can you please assign me this issue under gssoc'24

### Use Case

It will Increase Website Attractiveness and Responsiveness

### Add ScreenShots

![ggg](https://github.com/singodiyashubham87/Draw-it-out/assets/161804629/986cffae-5446-4bc1-a58d-5ccfc08bf4e7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hi there @sailaja-adapa 👋🏻 

Can you please elaborate us about adding icons? Because there's already Icons are present for Social links!

**Comment by sailaja-adapa** [comment]
@0xabdulkhalid I would like to add icons to home,news,about us links

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @0xabdulkhalid

**Comment by 0xabdulkhalid** [comment]
You're assigned @sailaja-adapa !

Make sure to follow contributing guidelines before making changes, create a PR once you've verified the changes you made.

**Comment by sailaja-adapa** [comment]
Thanks you @0xabdulkhalid
