### ISSUE TITLE
No option to save or export drawings: [FEAT]

### ISSUE THREAD

**Issue by aviral-hub** [singodiyashubham87/Draw-it-out#39]
**Problem:**
Users currently lack the ability to save or export their drawings from the website. This limitation prevents them from preserving their work and sharing it with others, resulting in frustration and inconvenience.

**Solution:**
Implement a feature that allows users to save their drawings directly from the website. Additionally, provide options for exporting drawings in various file formats (such as PNG, JPEG, or SVG) to facilitate sharing and compatibility with different devices and software.

**Alternative Solutions:**
1. Integration with cloud storage services (e.g., Google Drive, Dropbox) to enable automatic saving and backup of drawings.
2. Implementing a "Download" button that allows users to export their drawings directly to their device.
3. Providing a "Share" button that generates a shareable link or allows users to share their drawings directly to social media platforms.

**Additional Context:**
Adding this feature would greatly enhance the user experience, empowering users to preserve their creative work and share it with others effortlessly. It would also contribute to the overall usability and competitiveness of the website by addressing a common user need.

**Comment by porwalshreyaa** [comment]
Hey, please assign this issue to me.

**Comment by singodiyashubham87** [comment]
@aviral-hub Are you interested in working on the issue?

**Comment by Bhumika1312** [comment]
Hi @singodiyashubham87,

Could you please assign the task related to issue resolution to me? I am eager to work on it.

Here are the steps I plan to take:

1. Add two buttons to the HTML. One button will clear the canvas, and the other will save the drawing.
2. Make some changes in the JavaScript to set up event listeners for mouse events.

Thank you.

**Comment by DownOnCoffee** [comment]
Please assign me this task, I am an experienced frontend developer. I have worked with exporting and saving files before thus It will be an easy task for me!

**Comment by krishna-singha** [comment]
I am interested in this issue please assign to me

**Comment by sapana1579** [comment]
@singodiyashubham87 Hello,

I like this project idea and wants to work on this project. Kindly assign me this issue under GSSoc'24.

**Comment by codebreaker3008** [comment]
@singodiyashubham87 
Could you assign this to me, as I can help you as I have an idea what to do here

**Comment by singodiyashubham87** [comment]
@aviral-hub Since you haven't replied till now, I'm assigning the issue to the next interested person.

**Comment by singodiyashubham87** [comment]
@Aanya10Mishra I've assigned you the issue, Best of Luck!

**Comment by Aanya10Mishra** [comment]
Thanks a lot @singodiyashubham87...looking forward to it! BTW whom do I have to ask in case of any doubt

**Comment by singodiyashubham87** [comment]
@Aanya10Mishra You can tag me on the GSSOC server. Soon there will be a separate channel for Draw-it-out, after that you can ask all your doubts and queries there only.
Me or the mentors will assist you.

**Comment by singodiyashubham87** [comment]
@Aanya10Mishra Are you working on the issue or should I assign it to the next contributor?

**Comment by Aanya10Mishra** [comment]
yeah...i am.

**Comment by Aanya10Mishra** [comment]
hey @singodiyashubham87 how may i get in contact with you? I'm little confused.

**Comment by singodiyashubham87** [comment]
@Aanya10Mishra Yeah, Sure. 
You can reach me out on discord (#singodiyashubham87) or the mentor ( #0xabdulkhalid )

**Comment by singodiyashubham87** [comment]
@Aanya10Mishra It's been 2 weeks any update?

**Comment by Bhumika1312** [comment]
@singodiyashubham87 Can you please assign this issue to me I also want to work on this issue under GSSOC'24

**Comment by singodiyashubham87** [comment]
I am unassigning due to inactivity.

**Comment by singodiyashubham87** [comment]
@Bhumika1312 How are you going to approach the export drawing feature?

**Comment by Bhumika1312** [comment]
@singodiyashubham87 
Here are the steps I plan to take:

1. Add two buttons to the HTML. One button will clear the canvas, and the other will save the drawing.
2. Make some changes in the JavaScript to set up event listeners for mouse events.

I will try my best to complete this task

**Comment by singodiyashubham87** [comment]
@Bhumika1312 Both these functionalities for clearing the canvas & saving the drawing are already there, We need a feature to share the drawing with someone.

**Comment by porwalshreyaa** [comment]
> We need a feature to share the drawing with someone

By saving it in drive?
Can I take this?

**Comment by singodiyashubham87** [comment]
@porwalshreyaa Hold on, Please.
If Bhumika is not ready to take up the issue then I will pass it on to you.

**Comment by Bhumika1312** [comment]
@singodiyashubham87 
I will follow these steps:
Step 1: Add a button to share the drawing.
Step 2: When the share button is clicked, use JavaScript to convert the canvas drawing to a data URL.
Step 3: Use the data URL to display the drawing in a new tab or allow the user to download it.

**Comment by singodiyashubham87** [comment]
@Bhumika1312 But we don't want the image to open in a new tab or to download the image.
We want to share it with someone, for instance, I created something & I want to share it with my friend I want a button to click and the drawing is saved somewhere (ex. drive) & then I'll get a link to share with my friend.

**Comment by Bhumika1312** [comment]
We can use a cloud storage API, like Google Drive API, directly from your JavaScript to implement this.

**Comment by porwalshreyaa** [comment]
@Bhumika1312 If you are unsure then we can collab on this issue.

**Comment by porwalshreyaa** [comment]
> @Bhumika1312 But we don't want the image to open in a new tab or to download the image. We want to share it with someone, for instance, I created something & I want to share it with my friend I want a button to click and the drawing is saved somewhere (ex. drive) & then I'll get a link to share with my friend.

If you allow it, I and Bhumika can together complete this feature.

**Comment by singodiyashubham87** [comment]
@porwalshreyaa @Bhumika1312 Very well then, I'm assigning you both the issue. You both can make co-author commits & when you create a PR, Do mention me & ask me to assign that PR to both of you.
Best of Luck :)

**Comment by Bhumika1312** [comment]
@singodiyashubham87 Sure and Thank you

**Comment by porwalshreyaa** [comment]
@Bhumika1312 ping me on discord, we'll chat there.

**Comment by Bhumika1312** [comment]
> @Bhumika1312 ping me on discord, we'll chat there.
Can you provide me your discord id

**Comment by porwalshreyaa** [comment]
> Can you provide me your discord id

anonymousfrog
