### ISSUE TITLE
[Feature Request]: Made with 💝 by Master Mickey! This text should be with copy right

### ISSUE THREAD

**Issue by Saipradyumnagoud** [singodiyashubham87/Draw-it-out#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Made with 💝 by [Master Mickey Should place this text in the footer

### Use Case

Changes the look of the project

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
Duplicate issue.

**Comment by Saipradyumnagoud** [comment]
@singodiyashubham87 can we connect in the discord

**Comment by Saipradyumnagoud** [comment]
> Duplicate issue.

No this isuue is not there

**Comment by singodiyashubham87** [comment]
@Saipradyumnagoud Oh, Sorry. It was my mistake.
