### ISSUE TITLE
[FEAT]:No option for adding Texts

### ISSUE THREAD

**Issue by Scrapper700** [singodiyashubham87/Draw-it-out#40]
Problem:
 It is difficult to use an online drawing board that lacks the option to add text. Nowadays, people frequently write text on the drawing board, while drawing can convey ideas visually, sometimes adding text annotations or labels is essential for clarity and communication. Without this feature, users may struggle to convey specific information or context within their drawings, leading to misunderstandings or confusion.

Solution:
I would like the online drawing board to include the option to add text to the canvas. This feature would allow users to insert text boxes, type in annotations, or label different parts of their drawings directly.

**Comment by porwalshreyaa** [comment]
Hey, can you please assign this issue to me? For GSSoC.

**Comment by Scrapper700** [comment]
Actually I wanted to begin my joruney of OS with this @porwalshreyaa.. @singodiyashubham87 Can you assign me this under GSSOC'24

**Comment by porwalshreyaa** [comment]
> Actually I wanted to begin my joruney of OS with this @porwalshreyaa.. @singodiyashubham87 Can you assign me this under GSSOC'24

Oh, I see, you didn't mention it... how would I know? :(

**Comment by Shashanka-22** [comment]
Hey, can you please assign this issue to me? For GSSoC.

**Comment by Scrapper700** [comment]
> > Actually I wanted to begin my joruney of OS with this @porwalshreyaa.. @singodiyashubham87 Can you assign me this under GSSOC'24
> 
> Oh, I see, you didn't mention it... how would I know? :(

My apologies, it seems I made a mistake. I'm new to this field and wasn't aware that I needed to comment :_(

**Comment by singodiyashubham87** [comment]
@Scrapper700 Assigned!
Best of Luck!

**Comment by singodiyashubham87** [comment]
@porwalshreyaa I see you are too much willing to resolve issues, I have an issue for you if you are interested then check it out -> https://github.com/singodiyashubham87/Draw-it-out/issues/37

**Comment by Scrapper700** [comment]
@singodiyashubham87 Sorry!! Please unassign this task for me. I'm not sure what to use.

**Comment by singodiyashubham87** [comment]
@Shashanka-22 I have assigned the issue to you, Best of Luck!

**Comment by gundellyvamshiyadav** [comment]
I would like to work on this issue.Could you assign it to me.I want to start my first contribution under GSSOC'24.If not this issue assign me with another issue please and help me to start my open source journey.

**Comment by singodiyashubham87** [comment]
@gundellyvamshiyadav Assigned you the issue, Good Luck :)
Read the Contributing Guidelines first.

**Comment by singodiyashubham87** [comment]
@Sanj-bot Already assigned.

**Comment by singodiyashubham87** [comment]
Unassigned due to inactivity.

**Comment by singodiyashubham87** [comment]
@Sanj-bot Want to work on the issue?
