### ISSUE TITLE
[Bug]: Overlapping the Icon

### ISSUE THREAD

**Issue by theeayushkumar** [singodiyashubham87/Draw-it-out#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Icon overlapping 

### Expected behavior

Adjust Layout and Spacing

### Add ScreenShots

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/128235540/a1144f7b-f5fc-42d4-9ce7-7e3861de31d8)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@theeayushkumar Select one from GSSOC & SSOC.

**Comment by singodiyashubham87** [comment]
Duplicate of #253
