### ISSUE TITLE
[Feature Request]: Adding "ABOUT US" page (currently redirecting to nowhere)

### ISSUE THREAD

**Issue by HarshitGupta1511** [singodiyashubham87/Draw-it-out#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to "about us" page to the website, now when we click on the about us page it take us back to homepage, I want to add separate about page that tells about who we are, what we do and everything.

please assign this issue to me @si

### Use Case

when a user wants to know exactly what this website it all about, about us page will be a great source.

### Benefits

Easy to navigate directly to page where all info and uses of project is already elaborated.

### Add ScreenShots

<img width="1426" alt="Screenshot 2024-06-23 at 10 51 08 PM" src="https://github.com/singodiyashubham87/Draw-it-out/assets/120268295/f6848061-69e3-452d-a123-054035ac21ff">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@HarshitGupta1511 #226 is dealing with this same issue & it will be resolved soon.
