### ISSUE TITLE
[Feature Request]: implement codeql ci/cd workflow for `JavaScript`

### ISSUE THREAD

**Issue by harmeetsingh11** [singodiyashubham87/Draw-it-out#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The repository contains code in `JavaScript`, but it does not have a workflow for code scanning.

### Use Case

- The use case for this implementation is to enhance the security and quality of the codebase. By integrating CodeQL into the development workflow, any vulnerabilities or potential security issues in the JavaScript code will be automatically identified and flagged. 
- This proactive approach to code security ensures that any new code changes are thoroughly checked for security risks, thereby reducing the likelihood of vulnerabilities being introduced into the codebase. 
- This is especially useful for maintaining a high standard of code quality and security in projects where code changes are frequent and rapid, such as in continuous integration/continuous deployment (CI/CD) environments.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@harmeetsingh11 Select one from GSSOC & SSOC.

**Comment by harmeetsingh11** [comment]
@singodiyashubham87 assign me under `SSoC'24` program.

**Comment by singodiyashubham87** [comment]
@harmeetsingh11 Best of Luck :)
