### ISSUE TITLE
[Feature Request]: add content for home, about and contact page for more information

### ISSUE THREAD

**Issue by Vijayaa21** [singodiyashubham87/Draw-it-out#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add engaging and informative content to the About page, providing a comprehensive overview of our organization, its mission, and its values. Additionally, I intend to create a dedicated contact page to facilitate easy access for individuals seeking assistance, information, or offering valuable suggestions. This will enable seamless communication and collaboration with our audience, further enhancing our ability to address their needs and concerns.

### Use Case

By creating a dedicated "About" page and "Contact" section, users can gain insight into the app's use cases and features. Additionally, it provides a convenient way for users to initiate further discussions.Adding a specific about page and contact section helps the user to learn about the use cases of the app, its features, and to easily reach you for conversation.

### Benefits

Including these elements in the project would greatly assist users in understanding its purpose, unique features, and the individuals responsible for its creation.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@Vijayaa21 Sorry but we don't want any new page in this application.
