### ISSUE TITLE
[FEAT] : Add hovering effect over the  color icons .

### ISSUE THREAD

**Issue by souvik-maity** [singodiyashubham87/Draw-it-out#42]
**Describe the solution you'd like**
A hovering effect over the icons to make the UI look better. Also, add a border to the color while clicking.

**Comment by Chetan8299** [comment]
I would love to contribute to this issue, as a GSSOC contributor

**Comment by souvik-maity** [comment]
Kindly assign this issue to me . I want to eagerly contribute to this.

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by singodiyashubham87** [comment]
@souvik-maity Do you want to work on the issue?

**Comment by souvik-maity** [comment]
Yes , I want to work on this.

**Comment by singodiyashubham87** [comment]
@souvik-maity Best of Luck!

**Comment by souvik-maity** [comment]
Thanks

**Comment by paridhi1509** [comment]
@singodiyashubham87 Please assign this issue to me
