### ISSUE TITLE
Dropdown autoclose

### ISSUE THREAD

**Issue by Jasleen1210** [singodiyashubham87/Draw-it-out#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Many of the dropdowns in the toolbar do not have the feature of closing when clicked elsewhere.

### Expected behavior

I would like to implement the autoclosing function in those dropdowns as it is irritating when dropdowns are hard to close 

I have searched for existing issues and found that a similar issue has been raised but only for the brush tool, may i work on the dropdowns of upload, shape and thickness tool?

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@Jasleen1210 Complete already assigned issues first.

**Comment by Utsavladia** [comment]
I would like to work on this issue if no one is assigned..

**Comment by singodiyashubham87** [comment]
@Utsavladia Proceed.
