### ISSUE TITLE
Chatbot for the web-app

### ISSUE THREAD

**Issue by Leorasaharia** [singodiyashubham87/Draw-it-out#43]
**Is your feature request related to a problem? Please describe.**

Users who interact with the drawing feature on the website may encounter challenges in finding assistance or guidance related specifically to drawing tasks. Additionally, there is a lack of functionality for easily exporting drawn images and a missing undo/redo option, which can hinder the user experience and workflow.

**Describe the solution you'd like**

To address these issues, I propose the following solutions:

1. **Pop-up Chatbot for Drawing Assistance:**
   - Implement a small pop-up chatbot that provides assistance and answers questions related specifically to drawing tasks.
   - The chatbot should offer guidance on using drawing tools, selecting colors, and executing various drawing techniques to help users enhance their drawing skills.

2. **Export Button with Toggle Feature:**
   - Add a button on the landing page with a toggle feature that allows users to navigate and export their drawings.
   - Upon toggling the export feature, users should be able to take a screenshot of their drawing, and a pop-up window should prompt them to save the image locally on their computer.

3. **Undo/Redo Functionality with Partial Undo:**
   - Introduce undo and redo options that enable users to revert or replay their drawing actions.
   - Implement a partial undo feature where, instead of wiping out the entire drawing with each undo action, the drawing should revert to its previous state in stages. For example, if a user drew a mountain in steps (outline, coloring, shading), undoing an action should revert the drawing to the previous stage rather than erasing everything at once.

**Describe alternatives you've considered**

An alternative solution could involve integrating a comprehensive drawing tutorial or guide within the website to assist users in mastering drawing techniques. Additionally, instead of a pop-up chatbot, providing a dedicated help section with FAQs and tutorials could address user queries related to drawing tasks.

**Additional context**

Implementing these features will enhance the drawing experience on the website by providing users with on-demand assistance, streamlined export functionality, and improved control over their drawing process with undo/redo options. These enhancements aim to make the drawing feature more intuitive, user-friendly, and conducive to creative expression.

**Comment by Leorasaharia** [comment]
@singodiyashubham87 kindly consider my views on this! would be looking forward to contribute and enhance your project!

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by singodiyashubham87** [comment]
@Leorasaharia I see you have combined multiple functionalities in a single issue, we already have an open issue for undo/redo functionality and as of export one, there is an option to take snapshot which prompts the user to download the snapshot of the drawing.
Chat bot is something we can think of, do elaborate how will you proceed with the chatbot?

**Comment by Leorasaharia** [comment]
Just like I wrote there we can just implement a basic chatbot facility using react-chatbot-kit and feed the data only relevant to what a user wants to draw. For example a user wants to draw a simple sketch of a beautiful mountain scenery but is unsure about how to approach it, so the chatbot (draw bot rather) helps the person by guiding it what colors it can use or what type of drawing tools to use on the website. Not like a LLM model but rather a simple chatbot fed on some data relevant to the logistics about drawing a designer so.

**Comment by singodiyashubham87** [comment]
Seem interesting, Do you want to work on the issue ? @Leorasaharia

**Comment by Leorasaharia** [comment]
Yes sir, I would like to give it a try!

**Comment by singodiyashubham87** [comment]
@Leorasaharia Best of Luck!
