### ISSUE TITLE
[Feature Request]: Feat: Add Floating Social Media Iconbar

### ISSUE THREAD

**Issue by AsmitaMishra24** [singodiyashubham87/Draw-it-out#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a floating social media icon bar to the homepage of our website to improve user engagement by providing easy access to our social media profiles.

**Requirements**
1. Position: The icon bar should be positioned on the left side of the screen.
2. Visibility: The bar should remain visible when the user scrolls up and down the home screen.
3. Icons: Include icons for Facebook, Twitter, Instagram, LinkedIn, and YouTube.
4. Links: Each icon should link to the corresponding social media profile.
5. Responsive Design: The icon bar should be responsive and should adjust to different screen sizes (desktop, tablet, mobile).
6. Hover Effect: When a user hovers over an icon, it should display the name of the social media platform.
7. Accessibility: Ensure the icon bar is accessible and follows best practices for screen readers.

### Use Case

- Increased Social Media Engagement
- Enhanced User Experience
- Brand Visibility
- Content Sharing
- Customer Support and Feedback

### Add ScreenShots

![Social-Media-Icons-Hover-Effect](https://github.com/singodiyashubham87/Draw-it-out/assets/146121869/ccd03159-04de-4ca1-8894-c112ca573cd2)

https://github.com/singodiyashubham87/Draw-it-out/assets/146121869/517ec56c-c77e-4a3d-a89f-c906cda80c1f

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@AsmitaMishra24 There are already social media icons in the application, what's need of these floating ones?
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/93720428/73cf4964-2f3c-47b3-8068-97be46ebc0b7)

**Comment by AsmitaMishra24** [comment]
@singodiyashubham87, I think adding floating social media icons next to the drawing canvas will enhance the user experience, as most users do not scroll down to the footer; this feature will also look great, make it easier for users to connect and share their creations, increase user engagement, and efficiently use the space next to the canvas.

**Comment by singodiyashubham87** [comment]
@AsmitaMishra24 You are not, but see the other side of the coin too, It will distract the user from the canvas which is our real focus in the application.

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 You are not, but see the other side of the coin too, It will distract the user from the canvas which is our real focus in the application.

Ok, I understand
