### ISSUE TITLE
splash screen 

### ISSUE THREAD

**Issue by sheetal-81** [singodiyashubham87/Draw-it-out#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i wish to add the splash screen ,to make it looks more attractive 

### Use Case

just for the look and feel of page

### Benefits

user will found more eye-catchy page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@sheetal-81 Provide a prototype of splash screen.

**Comment by sheetal-81** [comment]
This is sample code and this is how it will be 
![first](https://github.com/singodiyashubham87/Draw-it-out/assets/134307985/762001c5-a0ba-4840-818a-6b76b8666ff7)
![sec](https://github.com/singodiyashubham87/Draw-it-out/assets/134307985/806ae972-078d-4e03-b83f-3a3ca3481027)

and this is code i can do maximum changes 
<!DOCTYPE html>
<html>

<head>
    <title>My Website</title>
    <style>
        /* CSS styles */
        .container {
            background-color:#DFFFFD;
            padding: 20px;
            margin: 50px auto;
            border: 15px solid white;
            display: grid;
            width: 80%;
            height:65%;
        }

        .splash {
            cursor: pointer;
            position: fixed;
            top: 50%;
            left: 50%;
            height: 95%;
            width: 95%;
            transform: translate(-50%, -50%);
            background-color: #DBD7D2;
            transition: all ease-in-out 600ms;
        }

        .hidden {
            display: none;
        }

        .splash-header {
            height: 90%;
            color: Black;
            font-family: consolas;
            font-size: 30px;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        body {
            background-color: #C9A0DC;
        }
    </style>
    <script>
        // JavaScript
        document.addEventListener('DOMContentLoaded', function () {
            var splashScreen = document.querySelector('.splash');
            splashScreen.addEventListener('click', function () {
                splashScreen.style.opacity = 0;
                setTimeout(function () {
                    splashScreen.classList.add('hidden');
                }, 610);
            });
        });
    </script>
</head>

<body>
    <div class="container">
        <h3>Hello World!!</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum numquam placeat commodi dicta nisi delectus
            voluptates, ratione rerum odit dolorem nulla tenetur eaque hic necessitatibus, voluptatem explicabo
            aperiam. Consectetur, deleniti.</p>
        
        <div class="splash">
            <h1 class="splash-header">Welcome to my Website!!</h1>
        </div>
        
    </div>
</body>

</html>

**Comment by singodiyashubham87** [comment]
@sheetal-81 This is not looking appealing at all, Sorry but we can't consider this.
