### ISSUE TITLE
[Bug]: Tutorial appears even if the website has already been accessed before.

### ISSUE THREAD

**Issue by LyubomirT** [singodiyashubham87/Draw-it-out#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The bug occurs because the website's tutorial is not properly tracking whether the user has already accessed the site before. As a result, the tutorial appears every time the user visits the website, regardless of whether they have seen it previously.

This issue likely arises from the lack of a mechanism to store and retrieve information about the user's previous visits or interactions with the tutorial. Without this tracking, the website treats each visit as a new session and displays the tutorial again.

Perhaps we should use cookies / localStorage to check if the website's been accessed before and hide the tutorial if that's true.

### Expected behavior

I think that the tutorial must be displayed on first visit, and hidden for all subsequent sessions.

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@LyubomirT Are you a GSSOC or SSOC contributor?

**Comment by LyubomirT** [comment]
Not yet. Is that a requirement?

**Comment by singodiyashubham87** [comment]
@LyubomirT Nopes! You can go ahead.

**Comment by LyubomirT** [comment]
Okay then, thank you! I'll create a PR when I finish working on this.
