### ISSUE TITLE
[Bug]: Icons not aligned perfectly

### ISSUE THREAD

**Issue by ankiiitagupta** [singodiyashubham87/Draw-it-out#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we click on eye icon, all the icons are not aligned in line correctly.

### Expected behavior

I can align them correctly. Please assign me this issue under GSSOC'24.

### Add ScreenShots

![Screenshot 2024-07-02 204242](https://github.com/singodiyashubham87/Draw-it-out/assets/108889476/eada0361-e541-4071-ac59-1fda0cd7a6a7)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@ankiiitagupta Kindly provide a recording of the issue.

**Comment by ankiiitagupta** [comment]
@singodiyashubham87 You can check it.

**Comment by singodiyashubham87** [comment]
@ankiiitagupta Assigned to you, Best of Luck :)
