### ISSUE TITLE
Feature Addition: Add Cursor Trail Effect To Look More Artistic

### ISSUE THREAD

**Issue by MastanSayyad** [singodiyashubham87/Draw-it-out#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @singodiyashubham87 

I would like to enhance the user experience on the "Draw it Out" website by adding an artistic **trail effect to the cursor**. This feature will make the website more engaging and visually appealing, aligning with its theme of canvas drawing.

I will make sure:
- It is smooth without lag.
- Aesthetically pleasing
- The trail effect does not interfere with other interactive elements on the page.
- It does not irritate to users instead it will be fun to play with!

Like This:

https://github.com/singodiyashubham87/Draw-it-out/assets/101971980/97bbc57e-3051-492f-89fe-2717a41a64a0

### Use Case

- The trail effect will provide a more interactive and artistic feel to the cursor, which fits the creative nature of the "Draw it Out" website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@MastanSayyad The trail will hinder the drawing area, how will you handle that?

**Comment by MastanSayyad** [comment]
@singodiyashubham87 simply by automatically hiding the trail effect whenever put on the canvas

The trail effect will only show outside canvas, while drawing it will not hinder any part

**Comment by MastanSayyad** [comment]
I can try it by putting some logics and conditions

**Comment by singodiyashubham87** [comment]
@MastanSayyad Okay, Proceed. Remember to use the app theme & not the pink color.

**Comment by MastanSayyad** [comment]
Yes, I'll make sure it follows website's design theme
