### ISSUE TITLE
[Bug]: Footer hover effects improvement

### ISSUE THREAD

**Issue by aanchalpahuja18** [singodiyashubham87/Draw-it-out#447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Footer hover effects color can be enhanced 

### Expected behavior

On hovering the links in the footer the color should be light since we are already having a dark background

### Add ScreenShots

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/136963878/82e80ecd-0f8f-4eaa-acc5-3dbd3d670062)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by aanchalpahuja18** [comment]
@singodiyashubham87 Kindly assign this issue to me I want to work on this.

**Comment by singodiyashubham87** [comment]
@aanchalpahuja18 How will you make it look like, provide a recording.

**Comment by aanchalpahuja18** [comment]
@singodiyashubham87 By adjusting the opacity or changing the color on hovering will help.

**Comment by vidipsingh** [comment]
https://github.com/singodiyashubham87/Draw-it-out/assets/112854574/46dd17b3-71d0-4512-9de9-21c02b360f4f

@singodiyashubham87 I have added a hover effect. Should I try to make the background color change when hovered over it?
For now I think it is pretty fine.

**Comment by 0xabdulkhalid** [comment]
Hey @aanchalpahuja18 👋🏻 

I assigned this issue to you, make sure to create a PR once you've made the changes!

**Comment by aanchalpahuja18** [comment]
@0xabdulkhalid Thankyou for assigning it to me I will definitely create a PR once the changes have been made!
