### ISSUE TITLE
[FEAT] Enhancing User Experience with Dark/Light Mode Toggle Button

### ISSUE THREAD

**Issue by ChaithanyaKrishna28** [singodiyashubham87/Draw-it-out#45]
**Is your feature request related to a problem? Please describe.**
Users may experience discomfort or eye strain when using the application in bright environments or during nighttime.

**Describe the solution you'd like**
Introduce a toggle button that allows users to switch between dark mode and light mode to accommodate different lighting conditions and personal preferences. In dark mode, the interface would feature darker colors and reduced brightness, while in light mode, it would revert to a traditional brighter color scheme.

**Describe alternatives you've considered**
Introducing a toggle button is the preferred solution. It provides users with direct control over the interface's appearance, allowing them to switch between dark mode and light mode based on their preferences and needs.

**Additional context**
Consider providing customization options for each mode, such as allowing users to adjust brightness levels or choose different color palettes. Additionally, ensure that the toggle button is easily accessible and intuitive to use, contributing to a seamless user experience.

@singodiyashubham87 please assign me(@ChaithanyaKrishna28 )this issue, I would love to contribute to it.

**Comment by Scrapper700** [comment]
Can you assign this task to me under GSSOC 24 @singodiyashubham87

**Comment by agxmbedi** [comment]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by singodiyashubham87** [comment]
@ChaithanyaKrishna28 Proceed!
Best of Luck!

**Comment by ritik7739** [comment]
Hello @singodiyashubham87 ,
 As a GSSOC 2024 contributor, I'm keen to tackle new challenges. 
 Please assign me this issue to showcase my skills and grow as a developer. 
 Thanks for considering me!

**Comment by ChaithanyaKrishna28** [comment]
> @ChaithanyaKrishna28 Proceed!
> Best of Luck!

I have completed the toggle mode feature and raised a Pull request please kindly check and merge the pr@singodiyashubham87

**Comment by ChaithanyaKrishna28** [comment]
I have completed the Mode-button functionality.
Please check and approve for the merge.I resolved the conflicts also.
