### ISSUE TITLE
[Feature Request]: Add Contact Us Form to the Website

### ISSUE THREAD

**Issue by TBorundia** [singodiyashubham87/Draw-it-out#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a "Contact Us" form to the website. This form will allow users to contact the team directly through the website. The form should include fields for the user's name, email address, and message, as well as a submit button.

There must be pop-up conformation message on submission as well as for invalid submission.

### Use Case

This feature would be beneficial for users who need to get in touch with the website's support team or provide feedback. It streamlines communication by providing a direct and easy way to reach out.

### Benefits

Improves user experience by providing an easy way to contact the team.
Enhances communication and feedback collection.
Can help in resolving user issues more efficiently.

### Add ScreenShots

![Screenshot 2024-07-07 145449](https://github.com/singodiyashubham87/Draw-it-out/assets/168854094/c3961822-4bf2-4b47-8b2c-5796a9a93ebf)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@singodiyashubham87 , please assign this issue to me under GSSoC'24.

**Comment by singodiyashubham87** [comment]
@TBorundia There is already an active issue related to the footer icons, kindly wait till it gets resolved #226

**Comment by TBorundia** [comment]
> @TBorundia There is already an active issue related to the footer icons, kindly wait till it gets resolved #226

@singodiyashubham87 ,
Ok Sir!

**Comment by VinayakPaka** [comment]
Can you assign it to me? I want to work on this issue.
