### ISSUE TITLE
[Feature Request]: Add hover effect to social media icons in footer

### ISSUE THREAD

**Issue by TBorundia** [singodiyashubham87/Draw-it-out#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding effects on social media icon oh hover according to their logo color

### Use Case

Can add transition to the icons oh hovering 

### Add ScreenShots

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/168854094/3d936dfe-d08a-40e1-8597-a73964921871)

https://github.com/singodiyashubham87/Draw-it-out/assets/168854094/8220859d-27b7-4bbb-a718-1b5d964d0b8f

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@singodiyashubham87 Sir, Please assign this issue to me under GSSoC'24.
Thank You!

**Comment by singodiyashubham87** [comment]
@TBorundia Try to make the hover effect look appealing & soothing.

**Comment by gaurav1603** [comment]
please assign to me
