### ISSUE TITLE
[FEAT] : improve the seo by adding the meta elements

### ISSUE THREAD

**Issue by 0xabdul** [singodiyashubham87/Draw-it-out#46]
Currently the Draw it out website lacks important meta elements so will affect seo problem
- by adding the meta tag like description, keywords, author using the meta tags to improve the seo problem

**Comment by singodiyashubham87** [comment]
@0xabdul Do you want to work on the issue?

**Comment by thatsyogeshjjr** [comment]
Sorry, for 2 PRs. I forgot to change my main branch and what had to be 2 separate PRs came to same branch

**Comment by 0xabdul** [comment]
> @0xabdul Do you want to work on the issue?

yes i work

**Comment by singodiyashubham87** [comment]
@0xabdul Best of Luck!
