### ISSUE TITLE
Feature🌟: Add a Dedicated "About us" Page For DrawItOut 

### ISSUE THREAD

**Issue by aslams2020** [singodiyashubham87/Draw-it-out#462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @singodiyashubham87,

Here is the feature request i want to suggest -

Currently, in the Footer their is an "Unlinked Text" named "About Us".
I want to create a dedicated "About us" Page Which will include all the Introductory Information about the Project and the website.

This is where i will add the Page - 

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/131389695/1a60f29d-82ae-4a98-bc71-b7ebcef18562)

Please assign me the issue under GSSoC'24.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by aslams2020** [comment]
@singodiyashubham87 I'd like to contribute to this feature

**Comment by singodiyashubham87** [comment]
@aslams2020 Already being worked upon in #234
