### ISSUE TITLE
[BUG] : Buttons are not Accessable

### ISSUE THREAD

**Issue by sivaprasath2004** [singodiyashubham87/Draw-it-out#47]
**Describe the bug**
Currently the `svg` elements are acting as `button` elements, it's  not accessible. We want to use actual `button` elements.

**To Reproduce**
1. Go to Draw it out website
2. Click on button elements to inspect them using Browser dev tools.
3. Scroll down and see the `svg` elements acting as button 

**Expected behavior**
 - The `svg` elements are need to be wrapped with `button` elements to improve accessability.

**Screenshots**
![Screenshot from 2024-05-10 20-57-02](https://github.com/singodiyashubham87/Draw-it-out/assets/121082414/21b846e0-9894-4ef5-82e2-14f31b75a527)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : chrome

**Smartphone (please complete the following information):**
 - Device: Realme 8
 - OS: Android 13
 - Browser: chrome

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 Want to work on the issue?

**Comment by thatsyogeshjjr** [comment]
I've quite near to the solution, it'd be nice if you'd assign me here

**Comment by siddhima22** [comment]
@singodiyashubham87 could I be assigned to this issue

**Comment by Aanya10Mishra** [comment]
hey ! i would like to work on this....Could you please assign this to me?

**Comment by sivaprasath2004** [comment]
Thank you @singodiyashubham87 . Yes , I want to work on this

**Comment by singodiyashubham87** [comment]
@sivaprasath2004 Best of Luck!
