### ISSUE TITLE
[Bug]: Can add a new, better, and more visible logo.

### ISSUE THREAD

**Issue by sweta-singh28** [singodiyashubham87/Draw-it-out#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current logo is not sufficiently visible and does not meet our quality standards. A new logo that is more visible and aesthetically pleasing should be designed and implemented.

### Expected behavior

I would like to take on the task of designing a more prominent and visually appealing logo. Enhancing the logo's visibility and overall design will significantly benefit the project. Please assign this issue to me so I can get started on creating a better logo. Thank you!

### Add ScreenShots

![Screenshot 2024-07-16 211916](https://github.com/user-attachments/assets/901fe13a-6728-4366-9486-2b6620b526c9)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sanjanah8** [comment]
Can u assign me to this issue

**Comment by singodiyashubham87** [comment]
@sweta-singh28 Show the logo which you made.

**Comment by sweta-singh28** [comment]
@singodiyashubham87 Sir,  I would start working on making the logo as soon as this issue is assigned to me with the proper labels.
