### ISSUE TITLE
[Feature Request]: Add rating and Feedback

### ISSUE THREAD

**Issue by KomalSrivastava** [singodiyashubham87/Draw-it-out#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We can add rating and feedback to it so it will be easy communication between the admin and the user through which we can add improvement to the website.

Hey @singodiyashubham87  Assign me this issue i will work on it.

### Use Case

improve the website and make better communication , which is good for it.

### Benefits

Better communication and improvement.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
@KomalSrivastava There is already an issue open for rating. #385
