### ISSUE TITLE
[FEAT]: To select a functionality using a button click

### ISSUE THREAD

**Issue by a-khushal** [singodiyashubham87/Draw-it-out#49]
To select a functionality using a button click
example: click 8 to draw

**Comment by a-khushal** [comment]
@singodiyashubham87 can I work on this?

**Comment by thatsyogeshjjr** [comment]
Duplicate of #36

**Comment by singodiyashubham87** [comment]
@a-khushal I don't think there is a need of something like this, the buttons are enough to select specific tool.

**Comment by a-khushal** [comment]
ok
