### ISSUE TITLE
[Bug]: footer link is not working

### ISSUE THREAD

**Issue by Varsani2520** [singodiyashubham87/Draw-it-out#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

footer link is dummy 

### Expected behavior

footer link is dummy like contact team...

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@singodiyashubham87 ,assign me

**Comment by singodiyashubham87** [comment]
@Varsani2520 Don't spam contribution, If you want to contribute then follow the project template, describe the issue, solution, screenshots, everything clearly.
Best of luck for further contributions.
