### ISSUE TITLE
[Feature Request]: changing drawing background to white

### ISSUE THREAD

**Issue by Sourabh782** [singodiyashubham87/Draw-it-out#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

White bachground also suits for using image on documents

### Use Case

many different use cases eg  your sign on documents etc

### Add ScreenShots

![Screenshot 2024-08-01 185505](https://github.com/user-attachments/assets/e767af78-dc75-4aa1-bd44-f2e5c0968f05)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment]
There is not an actual significance to this change, there is already option to change the Background.
