### ISSUE TITLE
NOT Responsive Header for all devices and content overlaps

### ISSUE THREAD

**Issue by Utsavladia** [singodiyashubham87/Draw-it-out#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/d59d09fb-83e4-44c8-85a3-94a2bea10e4f)

### Expected behavior

It should have proper spacing 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
### Hi there @Utsavladia 👋🏻 

Thank you for rising this issue regarding Responsiveness, this issue must needs to be addressed.

I'm assigning this to you, don't forget to test locally the changes you made before creating a PR.

Thank You!
