### ISSUE TITLE
[FEAT] UI Update, the current size of canvas is too small

### ISSUE THREAD

**Issue by thatsyogeshjjr** [singodiyashubham87/Draw-it-out#57]
## Problem
The current canvas size is too small, not allowing the application canvas to be used to its full potential.

## Solution
Increase the canvas size to fill in the entire screen. The buttons and color picker can be overlaid on top of it.

## Alternate solution
Increase the canvas size to fill in just enough of the screen, push the UI elements aside and allow the canvas to be scaled as per user requirement. Adding scrollbars

**Comment by thatsyogeshjjr** [comment]
REQUEST: I'd like to be assigned to this, if the feature seems plausible

**Comment by singodiyashubham87** [comment]
@thatsyogeshjjr Duplicate issue of #37
