### ISSUE TITLE
[FEAT] Additional Export option(s)

### ISSUE THREAD

**Issue by thatsyogeshjjr** [singodiyashubham87/Draw-it-out#58]
## Problem
Can't export images with transparent background

## Solution
Ignore the background color and allow user to save what he has drawn as PNG file

**Comment by thatsyogeshjjr** [comment]
REQUEST, I'd like to be assigned to this. If it seems plausible.

**Comment by singodiyashubham87** [comment]
@thatsyogeshjjr Proceed! 
Best of Luck!
