### ISSUE TITLE
[FEAT] Add Brush Strokes

### ISSUE THREAD

**Issue by thatsyogeshjjr** [singodiyashubham87/Draw-it-out#60]
## Problem
The current software only allows for one pen to draw

## Solution
Adding more brush strokes, pens, textures to be used in the canvas

**Comment by singodiyashubham87** [comment]
@thatsyogeshjjr Thanks for creating the issue, You are already assigned an issue, kindly resolve it first, then after I'll assign this issue to you if no one else has asked before that.

**Comment by sapana1579** [comment]
@singodiyashubham87 Hello, I like your project idea and want to work on this project. Kindly assign me this issue under GSSoC'24

**Comment by Harshitazz** [comment]
assign me

**Comment by singodiyashubham87** [comment]
@sapana1579 I've assigned you the issue, Best of Luck!

**Comment by sapana1579** [comment]
@singodiyashubham87 You can unassign this issue from me as I dont have required skill set to resolve it till now...but I assure to acquire it soon.

**Comment by shwetamishra4** [comment]
@singodiyashubham87 hello I like to work on this issue #60 please assign this task to me under GSSoC'24 .

**Comment by singodiyashubham87** [comment]
@Harshitazz Assigned you the issue, You may proceed.

**Comment by Harshitazz** [comment]
i am
