### ISSUE TITLE
custom canvas background color picker

### ISSUE THREAD

**Issue by siddxharth1** [singodiyashubham87/Draw-it-out#61]
we can add a feature in which we can choose custom background color

**Comment by singodiyashubham87** [comment]
@siddxharth1 But there is already this feature of choosing background color from the color palattes on the left side of canvas. Will you please elaborate what new change you wanna do?

**Comment by siddxharth1** [comment]
we have limited number of color there. i want to add a custom color picker similar to pen color

**Comment by singodiyashubham87** [comment]
@siddxharth1 Fair enough, You can start working on the issue.
But make sure that the style aligns with the web-app.
