### ISSUE TITLE
Add footer with social media icons

### ISSUE THREAD

**Issue by Asl2027** [singodiyashubham87/Draw-it-out#62]
**Is your feature request related to a problem? Please describe.**
Users currently do not have easy access to information about the creator of the app, which limits their ability to engage or connect with them beyond the app itself.

**Describe the solution you'd like**
Add social media icons at the end of the webpage for easy access to the creator's social media profiles. This will enable users to learn more about the person behind the app, fostering a stronger connection and potentially encouraging further engagement.

**Describe alternatives you've considered**
An alternative could be adding a "About the Creator" section within the app, but this may not be as readily accessible as social media icons placed at the end of the webpage.

**Additional context**
The social media icons could include links to platforms such as LinkedIn, Facebook, or Twitter, allowing users to explore the creator's professional background, interests, and updates. By implementing this feature, users can establish a more personal connection with the creator of the Draw it out app.

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/150686467/4364d215-ba4e-41c1-904d-44de3e1b30cb)

**Comment by Asl2027** [comment]
Kindly assign this issue to me. I can fix it @singodiyashubham87 .

**Comment by psychic-coder** [comment]
Hello I am Rohit Ganguly , I am a Full-Stack Developer ,I would like contribute to this issue can you please assign me this project under GSSoC'24. I have a proposed solution of creating an entire footer  for this page .

**Comment by singhpratibha98** [comment]
Kindly, assign this project to me . I want to contribute into this project .

**Comment by singodiyashubham87** [comment]
@Asl2027 Assigned you the issue.
Best of Luck!

**Comment by abhayprtp** [comment]
Kindly assign this issue to me. I can fix it @singodiyashubham87

**Comment by Niharika-Behera** [comment]
Kindly assign this issue to me.I can fix it.@singodiyashubham87

**Comment by singodiyashubham87** [comment]
@abhayprtp @Niharika-Behera This issue is already assigned, please choose another ones or raise new issues.

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by sreehithaAdari** [comment]
Hey!I want to work on this issue!Please assign me the task.

**Comment by singodiyashubham87** [comment]
@sreehithaAdari @somrima-09 This issue is already assigned to someone. Kindly explore other issues or raise new issues.

**Comment by singodiyashubham87** [comment]
@Asl2027 Are you working on the issue or should I assign it to the next contributor?

**Comment by Asl2027** [comment]
@singodiyashubham87 yes, I'm working on it. I'll turn in within 2 days.

**Comment by rahulkumarmutcherla** [comment]
I would like to work on it and i am very much fond of adding footer so i would like to request u to assign me this issue

**Comment by singodiyashubham87** [comment]
@rahulkumarmutcherla Someone is already working on the issue, kindly explore other issues.
@Asl2027 It has been more than 2 days, any updates?

**Comment by Asl2027** [comment]
@singodiyashubham87 I resolved the conflicts.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by bhaumik0307** [comment]
Kindly assign this issue to me. I can fix it @singodiyashubham87

**Comment by singodiyashubham87** [comment]
@bhaumik0307 Already assigned, kindly explore other issues.
