### ISSUE TITLE
Canvas Board is overlapping with color palette.

### ISSUE THREAD

**Issue by riteshjha61253** [singodiyashubham87/Draw-it-out#63]
**Describe the bug**
Canvas board is overlapping with the color palette after the screen size is reduced to less than 1270px.

**To Reproduce**
1. Go to 'Draw it out! website'
2. Right-click on mouse.
3. click inspect and reduce screen size

**Expected behavior**
The canvas board overlaps with the color palette.

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/117023896/f02337c1-b868-48a2-af27-eef9ef49c5a7)
**Desktop (please complete the following information):**
 - OS: [Window 11]
 - Browser [Edge]

I want to work on this issue can you please assign it to me?

**Comment by mukulpythondev** [comment]
@riteshjha61253  I wanna interested to fix the responsive issue in the Drawitout project

**Comment by riteshjha61253** [comment]
@singodiyashubham87 can you please assign this issue to me as I am really interested in this project.

**Comment by singodiyashubham87** [comment]
@riteshjha61253 Did you tried refreshing the page, I guess this issue is due to change in viewport size and not refreshing the page.

**Comment by singodiyashubham87** [comment]
@riteshjha61253 As you haven't replied since 3 days, I'm closing the issue.
