### ISSUE TITLE
[BUG]Unstable UI on Mobile devices while drawing on Whiteboard

### ISSUE THREAD

**Issue by suryapratapsingh26** [singodiyashubham87/Draw-it-out#64]
**Describe the bug**
There is an issue with the stability of the UI on mobile devices when drawing on the whiteboard. The UI seems to move up and down, possibly due to scrolling making it difficult to use.

**To Reproduce**
1. Go to the whiteboard feature on a mobile device.
2. Start drawing on the whiteboard.
3. Notice how the UI moves up and down, during drawing.
4. This instability persists throughout the drawing process.

**Expected behavior**
The UI should remain stable and not move up and down while drawing on the whiteboard.

**Smartphone (please complete the following information):**
 - Device: [iqneo6]
 - OS: [Android 12]
 - Browser [Chrome]

**Comment by suryapratapsingh26** [comment]
I want to work on this issue Under GSSOC'24. Assign me this issue

**Comment by suryapratapsingh26** [comment]
I want to work on this issue Under GSSOC'24. Assign me this issue

**Comment by singodiyashubham87** [comment]
@suryapratapsingh26 Assigned!
Best of Luck!

**Comment by suryapratapsingh26** [comment]
thank you! I will try to fix this issue as soon as possible

**Comment by suryapratapsingh26** [comment]
I have fixed the issue and had created a pull request but I have seen my
name is not listed as your mentee. Could you please advise on the next
steps I should I take to rectify this? Your assistance in addressing this
matter would be greatly appreciated.
Kind regards
