### ISSUE TITLE
[FEAT] Allow users to export their creations in various formats

### ISSUE THREAD

**Issue by Madhu-mac** [singodiyashubham87/Draw-it-out#65]
**Is your feature request related to a problem? Please describe.**

Export Options: Allow users to export their creations in various formats (PNG, JPEG, SVG, PDF) and resolutions.

**Describe the solution you'd like**

We can add options to the save image with different options like save as PNG, JPEG, SVG, PDF,JPG etc.

**Comment by singodiyashubham87** [comment]
@Madhu-mac Duplicate of #34

**Comment by Madhu-mac** [comment]
> @Madhu-mac Duplicate of #34 

Okay didn't saw that. Thanks for the gist
