### ISSUE TITLE
Add a navbar to this 

### ISSUE THREAD

**Issue by anshulsoni4** [singodiyashubham87/Draw-it-out#66]
**Is your feature request related to a problem? Please describe.**
the webpage seems to have no navbar

**Describe the solution you'd like**
create a responsive navbar

**Describe alternatives you've considered**

**Additional context**

**Comment by StephenStolk** [comment]
I want to take this up.

**Comment by JanitKumar** [comment]
assign this issue to me

**Comment by aasthakourav20** [comment]
Hey  singodiyashubham87 , Please assign this issue to me , I would like to add some new navbar features  with responsiveness .

**Comment by Mahy-31** [comment]
Hello there. As a GSOC'24 contributor, I want to take up this task and add a responsive navbar to your web page.

**Comment by singodiyashubham87** [comment]
@anshulsoni4 What is the need of navbar?

**Comment by codersurya04** [comment]
Please assign this to me

**Comment by anshulsoni4** [comment]
> @anshulsoni4 What is the need of navbar?

we need a navbar so that we can make about section, the panels there, drop down menu for more features, and it will be concluded through a side panel and a header

**Comment by Nih1tGupta** [comment]
Hi there, kindly assign me this issue, I am willing to work on this under the GSSOC tag.
Please checkout my previous work on this stuff.
https://github.com/singodiyashubham87/Draw-it-out/assets/119615342/fdf015c4-420c-43cf-abf6-c17768cd62c6

**Comment by singodiyashubham87** [comment]
@anshulsoni4 But it's not a conventional website, it's just a whiteboard app and we don't require about  section, and all as of now at least, closing the issue.
Thanks for raising :)
