### ISSUE TITLE
Adding a footer 

### ISSUE THREAD

**Issue by anshulsoni4** [singodiyashubham87/Draw-it-out#67]
**Is your feature request related to a problem? Please describe.**
no footer !

**Describe the solution you'd like**
make a footer with social icons

**Describe alternatives you've considered**

**Additional context**

**Comment by aakrati14** [comment]
Could you please assign this issue to me under GSSOC 24.
 I am eager to take on this task of improving our website by adding a footer.

**Comment by anshulsoni4** [comment]
> Could you please assign this issue to me under GSSOC 24. I am eager to take on this task of improving the website by adding a footer.
> 
> -I have read the Contributing Guidelines * -I have starred the repository *

but i have already marked it

**Comment by Mahy-31** [comment]
Hello there. 
I want to take up this task as a GSSOC'24 contributor. Kindly check my github profile for my projects.

**Comment by singodiyashubham87** [comment]
@anshulsoni4 I've already assigned you an issue & hence proceeding to the next interested person.

**Comment by singodiyashubham87** [comment]
@aakrati14 I've assigned you this issue, Best of Luck!

**Comment by anshulsoni4** [comment]
> @anshulsoni4 I've already assigned you an issue & hence proceeding to the next interested person.

why can you not assign one more !?
if i am coming with these ideas

**Comment by singodiyashubham87** [comment]
@anshulsoni4 This is how open-source works, Mate.
If I assign you multiple issues at the same time then others will never get the chance to contribute.
Kindly follow the guidelines & Keep contributing :)
