### ISSUE TITLE
make the color side panel in toggle style 

### ISSUE THREAD

**Issue by anshulsoni4** [singodiyashubham87/Draw-it-out#68]
**Is your feature request related to a problem? Please describe.**
the side panel could be openable

**Describe the solution you'd like**
make it open and close using button

**Describe alternatives you've considered**

**Additional context**

**Comment by singodiyashubham87** [comment]
@anshulsoni4 I've assigned you this issue, Best of Luck!

**Comment by anshulsoni4** [comment]
> @anshulsoni4 I've assigned you this issue, Best of Luck!

on it sir

**Comment by singodiyashubham87** [comment]
@anshulsoni4 It's been 3 weeks, any update?

**Comment by anshulsoni4** [comment]
> @anshulsoni4 It's been 3 weeks, any update?

sorry was busy with some hackathon stuff, if you want you can assing to someone else
