### ISSUE TITLE
add more background colors (custom color)

### ISSUE THREAD

**Issue by anshulsoni4** [singodiyashubham87/Draw-it-out#69]
**Is your feature request related to a problem? Please describe.**
there are few colors 

**Describe the solution you'd like**
make more colors or use pick color from brush or custom 

**Describe alternatives you've considered**

**Additional context**

**Comment by singodiyashubham87** [comment]
Do you want to work on the issue?

**Comment by singodiyashubham87** [comment]
@anshulsoni4 I've assigned you the issue, Best of Luck!

**Comment by singodiyashubham87** [comment]
Duplicate of #61
