### ISSUE TITLE
Add buy me a coffee or sponsor me button 

### ISSUE THREAD

**Issue by anshulsoni4** [singodiyashubham87/Draw-it-out#70]
**Is your feature request related to a problem? Please describe.**
there is no button for such action

**Describe the solution you'd like**
add button for sponsor

**Describe alternatives you've considered**

**Additional context**

**Comment by StephenStolk** [comment]
I want to take this up.

**Comment by aatmajajoshi** [comment]
Can u please assign me this issue, i want to work on it

**Comment by singodiyashubham87** [comment]
@StephenStolk I've assigned you this issue, Best of Luck!

**Comment by anshulsoni4** [comment]
> @StephenStolk I've assigned you this issue, Best of Luck!

hey @singodiyashubham87 i was the one who came up with this idea ig !?

**Comment by singodiyashubham87** [comment]
@anshulsoni4 Understand the rule buddy.
One can be assigned with only one issue at a time.

**Comment by anshulsoni4** [comment]
@singodiyashubham87 pls assign then

**Comment by singodiyashubham87** [comment]
@anshulsoni4 It's already assigned to someone, try to understand, buddy.
And you are already assigned #68 , You should resolve that first.

**Comment by StephenStolk** [comment]
@singodiyashubham87 
Please check the PR now.
