### ISSUE TITLE
[BUG] the ui is taking more width then the screen

### ISSUE THREAD

**Issue by AMISH-KHAN** [singodiyashubham87/Draw-it-out#76]
**Describe the bug**

The current UI is taking more width than the screen making it overflow horizontally

**Screenshots**

![Screenshot 2024-05-11 232243](https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/71af3708-8a54-4d00-a1c5-ff6280107146)

**Additional context**

please assign this issue to me under GSSOC and also add the necessary labels

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN I've assigned you this issue, Best of Luck!

**Comment by riteshjha61253** [comment]
@singodiyashubham87 can you please assign this issue to me.

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87 I have made the changes can you tell me on which branch should i push ?

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN You should create a new branch for your issue and then merge it to the main branch.

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87 I have made the PR #96. Please review it.

**Comment by AMISH-KHAN** [comment]
hey @singodiyashubham87 as the been merged can close this issue?
