### ISSUE TITLE
[BUG] not responsive

### ISSUE THREAD

**Issue by AMISH-KHAN** [singodiyashubham87/Draw-it-out#77]
**Describe the bug**

 The current ui lacks responsiveness and is not mobile friendly

**Video**

https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/a4caebe1-b696-4f93-9f02-1f363253bea9

**Additional context**

please assign this issue to me under gssoc and also add necessary labels

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN The UI is responsive, You just have to refresh the page once after changing screen size.

**Comment by manvichaudhary55** [comment]
I can make it responsive . Please assign this issue to me under gssoc'24 .

**Comment by singodiyashubham87** [comment]
@manvichaudhary55 The application is already responsive.
