### ISSUE TITLE
[BUG] Brush getting deselected after touching boundaries

### ISSUE THREAD

**Issue by kailashchoudhary11** [singodiyashubham87/Draw-it-out#80]
If I try to draw something and hit the boundaries, the brush gets deselected.

**Comment by mukulpythondev** [comment]
I wanna work on this issue

**Comment by Harshitazz** [comment]
i want to work

**Comment by singodiyashubham87** [comment]
@mukulpythondev Assigned!

**Comment by singodiyashubham87** [comment]
@mukulpythondev Are you working on the issue or should I assign it to the next contributor?

**Comment by mukulpythondev** [comment]
@singodiyashubham87 yes I worked on the issue but not able to solve you can assign to next contributor.

**Comment by The-Phoenics** [comment]
Hey @singodiyashubham87,
I would like to work on this. Can you assign this to me?

**Comment by singodiyashubham87** [comment]
@The-Phoenics Assigned! Best of Luck :)
