### ISSUE TITLE
LOGO FOR WEBSITE

### ISSUE THREAD

**Issue by Nih1tGupta** [singodiyashubham87/Draw-it-out#81]
**Is your feature request related to a problem? Please describe.**
**_A logo is the visual cornerstone of a website, embodying its identity and fostering immediate recognition and trust among users. It serves as a powerful symbol, encapsulating the essence of a brand and guiding the overall design and user experience._**
**Describe the solution you'd like**
**An eye catching logo must be present for this website**
**Describe alternatives you've considered**
**Also Some effects can be considered on hovering logo**
**Additional context**
![logoo](https://github.com/singodiyashubham87/Draw-it-out/assets/119615342/21ec18cc-6d5c-4795-8acc-f87e2099beca)

**Comment by Nih1tGupta** [comment]
Hi. Under GSSOC'24, I would like to work on this issue

**Comment by singodiyashubham87** [comment]
@Nih1tGupta Assigned the issue to you, make sure the logo looks appealing.
Best of Luck!

**Comment by hritika2409** [comment]
Please Assign me this task .I can workfor this

**Comment by somrima-09** [comment]
Hi. Under GSSOC'24, I would like to work on this issue.
Please Assign me this task.

**Comment by singodiyashubham87** [comment]
@hritika2409 @somrima-09 Already assigned to someone. Kindly raise new issues.

**Comment by singodiyashubham87** [comment]
@hritika2409 Want to work on the issue?

**Comment by hritika2409** [comment]
Yes I would be really glad if you assign me this issue.

**Comment by soumya-maheshwari** [comment]
Hello @hritika2409 
assigned the issue to you
Good luck !!

**Comment by hritika2409** [comment]
@soumya-maheshwari Thank you so much.I just need one help.Where can i contact you if i have many ideas and need your suggestions too.

**Comment by singodiyashubham87** [comment]
@hritika2409 You can contact @soumya-maheshwari on discord, Her discord username is "soumyamaheshwari"

**Comment by singodiyashubham87** [comment]
@Sanj-bot Hritika is already working on the issue, So you can't.

**Comment by BhumikaRahwani** [comment]
Hi @singodiyashubham87 , If the logo is not finalized yet, can u plz give me a chance to work on this issue and make a user interactive and appealing logo out here!!

**Comment by BhumikaRahwani** [comment]
I would like to work as a SSOC contributor.
