### ISSUE TITLE
[FEAT] Option to insert multiple pages 

### ISSUE THREAD

**Issue by Vaibhav2154** [singodiyashubham87/Draw-it-out#83]
Problem:
Not able to retrieve the old page as soon as the color of the page is changed.
Solution:
Adding a new button for the user to open multiple sheets so that the board can be used flawlessly with out encountering the above problem.

**Comment by Vaibhav2154** [comment]
Please assign me this issue under Gssoc'24

**Comment by singodiyashubham87** [comment]
@Vaibhav2154 There is already an issue open regarding this.

**Comment by Vaibhav2154** [comment]
Well I don't see anyone adding multiple pages option would be happy to work on that. 
Didn't go through the initial issues. Will be happy to work on any particular Issue in specific in future. Thank You.

**Comment by singodiyashubham87** [comment]
@Vaibhav2154 If there is nothing like this, then I'll assign you the issue in near future.
