### ISSUE TITLE
[FEAT] background colour pallette ui enhancement 

### ISSUE THREAD

**Issue by Harshitazz** [singodiyashubham87/Draw-it-out#84]
**Is your feature request related to a problem? Please describe.**
better ui and appealing

**Describe the solution you'd like**
make the pallete in a grid of two columns and giving more colour option by adding built in colour pallete (just like pen colour pallette)

![Screenshot 2024-05-12 121358](https://github.com/singodiyashubham87/Draw-it-out/assets/118474653/ed2c52b7-f7b3-4fc0-a9bc-67b296124746)
@singodiyashubham87  assign it to me

**Comment by riteshjha61253** [comment]
@singodiyashubham87 Can you Assign this issue to me so that I can start working on that.

**Comment by singodiyashubham87** [comment]
@Harshitazz There is already an issue regarding this. #61
