### ISSUE TITLE
Add proper heading, tagline & user guide.

### ISSUE THREAD

**Issue by GayathriThejus** [singodiyashubham87/Draw-it-out#88]
Problem:
Currently, the project lacks a proper heading and tagline on its UI, which affects its visual appeal and user experience. Also, it would be relevant to add a user guide highlighting on how to use the web app.

Solution:
Introduce a prominent heading at the top of the UI to provide users with a clear understanding of the application's purpose. Additionally, include a concise tagline underneath the heading to offer users a glimpse into the functionality & elevate the user experience to that of a standard web app. Add a user manual icon & show user guidelines in it.

![Screenshot (25)](https://github.com/singodiyashubham87/Draw-it-out/assets/114593358/c07cf870-a62a-4307-8f8b-3fcad5c63101)

**Comment by GayathriThejus** [comment]
Under GSSOC 24, Please assign the work to me!

**Comment by singodiyashubham87** [comment]
@GayathriThejus I have assigned you the issue, Best of Luck!

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
