### ISSUE TITLE
[FEAT] insert shape option 

### ISSUE THREAD

**Issue by sakshiiiii26** [singodiyashubham87/Draw-it-out#91]
Insert a bar containing different shapes which help user to insert any shape for his convenience.

**Comment by sakshiiiii26** [comment]
Hello @singodiyashubham87 I'm contributor of GSSoC 24. I request you to assign this task to me.

**Comment by riteshjha61253** [comment]
@singodiyashubham87 can you please assign this issue to me under GSSoC 24. So that I can Add this feature .

**Comment by singodiyashubham87** [comment]
@sakshiiiii26 How are you going to implement this functionality?

**Comment by sakshiiiii26** [comment]
1)Text option :-
Create button by HTML and CSS 
Use JavaScript event listener to detect when text tool is selected 
HTML and CSS to create input field 

2)Shape option :-
Create button for different shapes 
JavaScript to detect selection of shape tool and to draw the selected shape 

3)Multiple colour selection:-
Colour picker tool by HTML CSS 
Use JavaScript to store selected colour value and apply it.

And changing Position of some options and fixing the appropriate position of this feature by HTML/CSS and also changing its background.Also canvas API will be used and some libraries like Fabric.js will be used.

**Comment by singodiyashubham87** [comment]
@sakshiiiii26 Assigned you the issue, Best of Luck!

**Comment by singodiyashubham87** [comment]
@sakshiiiii26 I just saw that this issue is already open #33  and someone is already assigned, Please don't raise duplicate issues.
Closing the issue.

**Comment by sakshiiiii26** [comment]
> @sakshiiiii26 I just saw that this issue is already open #33 and someone is already assigned, Please don't raise duplicate issues. Closing the issue.

Sorry I didn't found this issue at that time I just go through the project and made this suggestion. And what about other two features??
@singodiyashubham87 can I work on other two features
