### ISSUE TITLE
[FEAT] Adding Labels

### ISSUE THREAD

**Issue by AMISH-KHAN** [singodiyashubham87/Draw-it-out#97]
**Is your feature request related to a problem? Please describe.**

currently the website does not have labels to the tools available

![Screenshot 2024-05-12 190758](https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/c5465e78-fa04-4575-ba4f-0a33987dd5b4)

**Describe the solution you'd like**

I suggest that we can add labels to them which will be easier for user to understand functionality of each tool 

![Screenshot 2024-05-13 003030](https://github.com/singodiyashubham87/Draw-it-out/assets/123164129/c7b19104-4d65-4bfe-80cc-c7378a1253b0)

**Additional context**
please assign this issue to me under GSSOC and add necessary labes

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN When you hover over the tools then the title becomes visible.

**Comment by AMISH-KHAN** [comment]
> @AMISH-KHAN When you hover over the tools then the title becomes visible.

you're right!! but it takes some time. Wouldn't it be better if we  just label them.

what you think??

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN I agree with your point too.

**Comment by singodiyashubham87** [comment]
@AMISH-KHAN Assigned you the issue, Best of Luck!

**Comment by AMISH-KHAN** [comment]
@singodiyashubham87 please review PR #106
