### ISSUE TITLE
[FEAT] Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [singodiyashubham87/Draw-it-out#98]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me.

**Comment by singodiyashubham87** [comment]
@sanmarg I've assigned the issue to you, Best of Luck!
Add this text too : "In the meantime you can star the repo and read the contributing.md file", something like this.
